---
title: "Stat Descriptive"
author: "Amélie Brejot"
date: "2024-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(ggplot2)
```

```{r}
df <- read.csv("df_desc.csv", stringsAsFactors = T)

colnames(df)
```

```{r}
str(df)
df$statut_recevant <- as.factor(df$statut_recevant)

```

# Regrouper par période
```{r}
data <- df %>%
  mutate(
    action = substr(as.character(action), 1, 3)
  ) %>%
  group_by(fichier) %>%
  mutate(
    periode = case_when(
      Temps_Sec >= 0 & Temps_Sec < 600 ~ 1,  # 0 - 10 minutes
      Temps_Sec >= 600 & Temps_Sec < 1200 ~ 2,  # 10 - 20 minutes
      Temps_Sec >= 1200 & Temps_Sec < 1800 ~ 3,  # 20 - 30 minutes
      Temps_Sec >= 1800 & Temps_Sec < 2400 ~ 4,  # 30 - 40 minutes
      Temps_Sec >= 2400 & Temps_Sec < 3000 ~ 5,  # 40 - 50 minutes
      Temps_Sec >= 3000 ~ 6,  # 50 - 60 minutes
      TRUE ~ NA_real_  # Valeur par défaut pour les autres cas (au cas où)
    )
  ) %>%
  ungroup()
data$statut_tm <- ""
data$statut_tm <- with(data,
  ifelse(action_equipe == "v",
         # Inverser les valeurs
         ifelse(as.character(statut_recevant) == "-1", "1",
                ifelse(as.character(statut_recevant) == "1", "-1", "0")),
         # Sinon, garder la valeur d'origine
         as.character(statut_recevant))
)


```

```{r}
ggplot(data = data[data$action == "Tem",], aes(x=as.factor(periode), fill = statut_tm)) +
  geom_bar() +
  labs(
    title = "Nombre de Temps-Mort pris par tranche de 10min selon le statut de l'équipe prenant le TM",
    x = "Période (1 période = 10 min)",
    y = "Nombre de Temps-Mort"
  ) +
  theme_minimal()
```

