---
title: "Machine learning"
author: "Amélie Brejot"
date: "2024-12-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rsample)
library(rpart)
library(rpart.plot)
library(caret)
```


# Arbres

```{r}
set.seed(123)
data <- read.csv("data_mod1.csv")
#summary(data)
data.split <- initial_split(data, prop = 3/4)
data.train <- training(data.split)
data.test <- testing(data.split)
```

```{r}
data$effet_positif <- as.factor(data$effet_positif)
data$TM_derniere_min <- as.factor(data$TM_derniere_min)
data$TM_derniere_min_adverse <- as.factor(data$TM_derniere_min_adverse)
data$HF <- as.factor(data$HF)
data$equipe <- as.factor(data$equipe)
data$DM_adverse <- as.factor(data$DM_adverse)
data$DM <- as.factor(data$DM)
data$statut_59_min <- as.factor(data$statut_59_min)
```


```{r}
control_params <- rpart.control(maxdepth = 30, minsplit = 2, cp = 0.0020)

tree <- rpart(effet_positif ~ TM_derniere_min + TM_derniere_min_adverse + HF + DM_adverse + DM + statut_59_min, data = data.train, method = "class", control = control_params)

plotcp(tree)
printcp(tree)

rpart.plot(tree)
```

Analyse d'une feuille (0, 0.15, 43%) :
La classe majoritaire choisie est pas d'effet positif pour le recevant (0)
Cette classe représente 15% de la feuille.
Cette feuille contient 43% du jeu de données.

```{r}
prediction <- predict(tree, data.test, type = "class")

data.test$effet_positif <- factor(data.test$effet_positif, levels = levels(prediction))

confusionMatrix(prediction, data.test$effet_positif)
```


