---
title: "Diff_point_norm"
author: "Amélie Brejot"
date: "2025-01-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Importation

```{r}
library(dplyr)
library(readr)
library(tidyverse)
```


# Classement par journée

```{r}
df <- read.csv("df_pdfs_N1_2.csv")
df <- df %>%
  separate(score_final, into = c("score_final_r", "score_final_v"), sep = "-") %>%
  mutate(
    score_final_r = as.integer(score_final_r),
    score_final_v = as.integer(score_final_v)
  )

df <- df %>%
  mutate(
    saison = str_extract(fichier, "\\d{4}"),           
    HF = str_extract(fichier, "[FH]"),              
    division = str_extract(fichier, "N\\d"),          
    match_num = str_extract(fichier, "_\\d+_\\d{4}") %>%
      str_extract("^\\d+")
  ) %>% 
  select(-match_num)

df <- df %>% select("code_rencontre","club_recevant","club_visiteur", "score_final_r", "score_final_v",
              "division","HF","saison", "journee", "fichier")

df_unique <- df %>%
  distinct(code_rencontre, .keep_all = TRUE)



for (i in 1:nrow(df_unique)){
  if (df_unique$score_final_r[i] > df_unique$score_final_v[i]) {
    df_unique$point_r[i] <- 3
    df_unique$point_v[i] <- 1
  } else if (df_unique$score_final_r[i] == df_unique$score_final_v[i]){
    df_unique$point_r[i] <- 2
    df_unique$point_v[i] <- 2
  } else if (df_unique$score_final_r[i] < df_unique$score_final_v[i]){
    df_unique$point_r[i] <- 1
    df_unique$point_v[i] <- 3
  }
}

points_par_club <- df_unique %>%
  select(code_rencontre,journee, division, saison, club = club_recevant, points = point_r, HF) %>%
  bind_rows(
    df_unique %>% select(code_rencontre,journee, division, saison, club = club_visiteur, points = point_v, HF)
  )

print(points_par_club)

points_par_club$journee <- as.factor(points_par_club$journee)
points_par_club$HF <- as.factor(points_par_club$HF)
points_par_club$division <- as.factor(points_par_club$division)
points_par_club$saison <- as.factor(points_par_club$saison)
points_par_club$points <- as.numeric(points_par_club$points)

summary(points_par_club$journee)

points_par_club <- points_par_club %>% 
  mutate(club = case_when(
    club == "BOUILLARGUES HANDBALL NIMES MEDITERRANEE" ~ "BOUILLARGUES HANDBALL NIMES METROPOLE",
    club == "C'CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
    club == "NANCY METROPOLE HB" ~ "NANCY METROPOLE",
    club == "NANCY HANDBALL" ~ "NANCY METROPOLE",
    club == "PAYS AIX UNIVERSITE CLUB HANDBALL" ~ "PROVENCE AIX UNIVERSITE CLUB HANDBALL",
    club == "VILLEURBANNE HANDBALL ASSOCIATION" ~ "VILLEURBANNE HANDBALL",
    club == "TREMBLAY EN FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
    club == "TREMBLAY-EN-FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
    club == "TOULON METROPOLE VAR HB" ~ "TOULON METROPOLE VAR HANDBALL",
    club == "BILLERE HANDBALL" ~ "BILLERE HANDBALL PAU PYRENEES",
    club == "CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
    club == "CAVIGAL NICE SPORTS HANDBALL" ~ "CAVIGAL NICE HANDBALL",
    club == "FRONTIGNAN HANDBALL" ~ "FRONTIGNAN THAU HANDBALL",
    club == "HBC NANTAIS" ~ "HBC NANTES",
    club == "MASSY ESSONNE HB" ~ "MASSY ESSONNE HANDBALL",
    club == "NOISY-LE-GRAND HANDBALL" ~ "NOISY LE GRAND HANDBALL",
    club == "HBC ST AMAND LES EAUX PORTE DU HAINAUT" ~ "ST AMAND HANDBALL - PORTE DU HAINAUT",
    club == "CHAMBERY SAVOIE MT-BLANC HB" ~ "CHAMBERY SAVOIE HB",
    club == "GRAND NANCY METROPOLE HB" ~ "GRAND NANCY METROPOLE HANDBALL",
    club == "LIMOGES HAND" ~ "LIMOGES HANDBALL",
    club == "SAINT RAPHAEL VHB" ~ "SAINT RAPHAEL VAR HANDBALL",
    club == "SARAN LOIRET HB" ~ "SARAN LOIRET HANDBALL",
    club == "DIJON METROPOLE HB" ~ "DIJON METROPOLE HANDBALL",
    club == "JS CHERBOURGEOISE MANCHE HB" ~ "JS CHERBOURGEOISE MANCHE HANDBALL",
    club == "E. STRASBOURG SCHILTIGHEIM ALSACE HANDBALL" ~ "STRASBOURG EUROMETROPOLE HB",
    club == "LIMOGES HANDBALL" ~ "LIMOGES",
    club == "LIMOGES HAND" ~ "LIMOGES",
    club == "ELITE VAL D'OISE" ~ "ELITE VAL-D'OISE",
    club =="ASSOCIATION SPORTIVE ST-OUEN-L'AUMONE HANDBALL" ~ "ASSOCIATION SPORTIVE ST-OUEN-L'AUMONE",
    club =="LILLE METROPOLE - HANDBALL CLUB VILLENEUVE D'ASCQ" ~ "LILLE METROPOLE - HANDBALL CLUB",
    TRUE ~ club
  )) %>% 
  filter(club != "SAINT-CYR VAR HANDBALL")

result <- points_par_club %>%
  select(club, division, saison, HF, journee, points) %>%
  pivot_wider(names_from = journee, values_from = points) %>% 
  arrange(HF, saison, division, club)

result$match_joue <- ""
for (i in 1:nrow(result)){
  result$match_joue[i] <- sum(is.na(result[i,]) == FALSE) -5
}
```

# Récupérer le résultat point par jour

```{r}
#write.csv(result, "point_jour_N1_2.csv")
```
NA dû à l'absence de certaine feuille de match.
Fichier complété à la main.


```{r}
point_jour <- read.csv("point_jour_N1_2.csv", row.names = 1, sep=";")
```


```{r}
for (i in 1:nrow(point_jour)){
  if (is.na(point_jour$J1[i]) == T){
    point_jour$J1[i] <- 0
  }
  for (j in 8:32){  # j = [J2:J6]
    if (is.na(point_jour[i,j-1])==T){
      point_jour[i,j-1] <- point_jour[i,j-2]
      point_jour[i,j] <- point_jour[i,j] + point_jour[i,j-1]
    } else {
      point_jour[i,j] <- point_jour[i,j] + point_jour[i,j-1]
    }
  }
  if(is.na(point_jour$J26[i])==T){
    point_jour$J26[i] <- point_jour$J25[i]
  }
  
}

point_jour$saison <- factor(point_jour$saison)
point_jour$division <- factor(point_jour$division)
```


# Ajout variable diff_point

```{r}
point_jour$J0 <- 0
point_jour <- point_jour %>% relocate('J0', .after = 'total_point')

for (j in 32:8){
  point_jour[,j] <- point_jour[,j-1]
}

point_jour <- point_jour %>%
  select(-J0) %>% 
  pivot_longer(cols = starts_with("J"), names_to = "journee", values_to = "points") %>%
  mutate(journee = toupper(journee))

point_jour <- point_jour %>%
  group_by(club) %>%                            
  filter(as.numeric(sub("J", "", journee)) <= match_joue) %>% 
  ungroup() 

write.csv(point_jour, "point_jour_final_N1.csv")
```


# Normaliser point par journée

```{r}
df <- read.table("df_pdfs_N1.csv", header = TRUE, sep = ",")
df <- df %>%
  separate(score_final, into = c("score_final_r", "score_final_v"), sep = "-") %>%
  mutate(
    score_final_r = as.integer(score_final_r),
    score_final_v = as.integer(score_final_v)
  )

df <- df %>%
  mutate(
    saison = str_extract(fichier, "\\d{4}"),           
    HF = str_extract(fichier, "[FH]"),              
    division = str_extract(fichier, "N\\d"),          
    match_num = str_extract(fichier, "_\\d+_\\d{4}") %>%
      str_extract("^\\d+")
  ) %>% 
  select(-match_num)

df <- df %>% 
  select("code_rencontre","club_recevant","club_visiteur", "score_final_r", "score_final_v",
                    "division","HF","saison", "journee", "fichier") %>%
  distinct(code_rencontre, .keep_all = TRUE)

df <- df %>% 
  mutate(club_recevant = case_when(
    club_recevant == "BOUILLARGUES HANDBALL NIMES MEDITERRANEE" ~ "BOUILLARGUES HANDBALL NIMES METROPOLE",
    club_recevant == "C'CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
    club_recevant == "NANCY METROPOLE HB" ~ "NANCY METROPOLE",
    club_recevant == "NANCY HANDBALL" ~ "NANCY METROPOLE",
    club_recevant == "PAYS AIX UNIVERSITE CLUB HANDBALL" ~ "PROVENCE AIX UNIVERSITE CLUB HANDBALL",
    club_recevant == "VILLEURBANNE HANDBALL ASSOCIATION" ~ "VILLEURBANNE HANDBALL",
    club_recevant == "TREMBLAY EN FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
    club_recevant == "TREMBLAY-EN-FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
    club_recevant == "TOULON METROPOLE VAR HB" ~ "TOULON METROPOLE VAR HANDBALL",
    club_recevant == "BILLERE HANDBALL" ~ "BILLERE HANDBALL PAU PYRENEES",
    club_recevant == "CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
    club_recevant == "CAVIGAL NICE SPORTS HANDBALL" ~ "CAVIGAL NICE HANDBALL",
    club_recevant == "FRONTIGNAN HANDBALL" ~ "FRONTIGNAN THAU HANDBALL",
    club_recevant == "HBC NANTAIS" ~ "HBC NANTES",
    club_recevant == "MASSY ESSONNE HB" ~ "MASSY ESSONNE HANDBALL",
    club_recevant == "NOISY-LE-GRAND HANDBALL" ~ "NOISY LE GRAND HANDBALL",
    club_recevant == "HBC ST AMAND LES EAUX PORTE DU HAINAUT" ~ "ST AMAND HANDBALL - PORTE DU HAINAUT",
    club_recevant == "CHAMBERY SAVOIE MT-BLANC HB" ~ "CHAMBERY SAVOIE HB",
    club_recevant == "GRAND NANCY METROPOLE HB" ~ "GRAND NANCY METROPOLE HANDBALL",
    club_recevant == "LIMOGES HAND" ~ "LIMOGES HANDBALL",
    club_recevant == "SAINT RAPHAEL VHB" ~ "SAINT RAPHAEL VAR HANDBALL",
    club_recevant == "SARAN LOIRET HB" ~ "SARAN LOIRET HANDBALL",
    club_recevant == "DIJON METROPOLE HB" ~ "DIJON METROPOLE HANDBALL",
    club_recevant == "JS CHERBOURGEOISE MANCHE HB" ~ "JS CHERBOURGEOISE MANCHE HANDBALL",
    club_recevant == "E. STRASBOURG SCHILTIGHEIM ALSACE HANDBALL" ~ "STRASBOURG EUROMETROPOLE HB",
    club_recevant == "LIMOGES HANDBALL" ~ "LIMOGES",
    club_recevant == "LIMOGES HAND" ~ "LIMOGES",
    club_recevant == "ELITE VAL D'OISE" ~ "ELITE VAL-D'OISE",
    club_recevant =="ASSOCIATION SPORTIVE ST-OUEN-L'AUMONE HANDBALL" ~ "ASSOCIATION SPORTIVE ST-OUEN-L'AUMONE",
    club_recevant =="LILLE METROPOLE - HANDBALL CLUB VILLENEUVE D'ASCQ" ~ "LILLE METROPOLE - HANDBALL CLUB",
    TRUE ~ club_recevant
  )) %>%
  filter (club_recevant != "HBC ST AMAND LES EAUX PORTE DU HAINAUT",club_visiteur != "SAINT-CYR VAR HANDBALL")

df <- df %>% 
  mutate(club_visiteur = case_when(
    club_visiteur == "BOUILLARGUES HANDBALL NIMES MEDITERRANEE" ~ "BOUILLARGUES HANDBALL NIMES METROPOLE",
    club_visiteur == "C'CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
    club_visiteur == "NANCY METROPOLE HB" ~ "NANCY METROPOLE",
    club_visiteur == "NANCY HANDBALL" ~ "NANCY METROPOLE",
    club_visiteur == "PAYS AIX UNIVERSITE CLUB HANDBALL" ~ "PROVENCE AIX UNIVERSITE CLUB HANDBALL",
    club_visiteur == "VILLEURBANNE HANDBALL ASSOCIATION" ~ "VILLEURBANNE HANDBALL",
    club_visiteur == "TREMBLAY EN FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
    club_visiteur == "TREMBLAY-EN-FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
    club_visiteur == "TOULON METROPOLE VAR HB" ~ "TOULON METROPOLE VAR HANDBALL",
    club_visiteur == "BILLERE HANDBALL" ~ "BILLERE HANDBALL PAU PYRENEES",
    club_visiteur == "CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
    club_visiteur == "CAVIGAL NICE SPORTS HANDBALL" ~ "CAVIGAL NICE HANDBALL",
    club_visiteur == "FRONTIGNAN HANDBALL" ~ "FRONTIGNAN THAU HANDBALL",
    club_visiteur == "HBC NANTAIS" ~ "HBC NANTES",
    club_visiteur == "MASSY ESSONNE HB" ~ "MASSY ESSONNE HANDBALL",
    club_visiteur == "NOISY-LE-GRAND HANDBALL" ~ "NOISY LE GRAND HANDBALL",
    club_visiteur == "HBC ST AMAND LES EAUX PORTE DU HAINAUT" ~ "ST AMAND HANDBALL - PORTE DU HAINAUT",
    club_visiteur == "CHAMBERY SAVOIE MT-BLANC HB" ~ "CHAMBERY SAVOIE HB",
    club_visiteur == "GRAND NANCY METROPOLE HB" ~ "GRAND NANCY METROPOLE HANDBALL",
    club_visiteur == "LIMOGES HAND" ~ "LIMOGES HANDBALL",
    club_visiteur == "SAINT RAPHAEL VHB" ~ "SAINT RAPHAEL VAR HANDBALL",
    club_visiteur == "SARAN LOIRET HB" ~ "SARAN LOIRET HANDBALL",
    club_visiteur == "DIJON METROPOLE HB" ~ "DIJON METROPOLE HANDBALL",
    club_visiteur == "JS CHERBOURGEOISE MANCHE HB" ~ "JS CHERBOURGEOISE MANCHE HANDBALL",
    club_visiteur == "E. STRASBOURG SCHILTIGHEIM ALSACE HANDBALL" ~ "STRASBOURG EUROMETROPOLE HB",
    club_visiteur == "LIMOGES HANDBALL" ~ "LIMOGES",
    club_visiteur == "LIMOGES HAND" ~ "LIMOGES",
    club_visiteur == "ELITE VAL D'OISE" ~ "ELITE VAL-D'OISE",
    club_visiteur =="ASSOCIATION SPORTIVE ST-OUEN-L'AUMONE HANDBALL" ~ "ASSOCIATION SPORTIVE ST-OUEN-L'AUMONE",
    club_visiteur =="LILLE METROPOLE - HANDBALL CLUB VILLENEUVE D'ASCQ" ~ "LILLE METROPOLE - HANDBALL CLUB",
    TRUE ~ club_visiteur
  )) %>%
  filter (club_visiteur != "HBC ST AMAND LES EAUX PORTE DU HAINAUT", club_visiteur != "SAINT-CYR VAR HANDBALL" )


df$saison <- factor(df$saison)

df <- df %>% filter(saison != 2425)

point_jour_final <- read.csv("point_jour_final_N1.csv", row.names=1)
point_jour_final$saison <- factor(point_jour_final$saison)

```



# Rajouter diff_point au dataframe

```{r}
df2 <- df %>% 
  left_join(point_jour_final, by = c("HF","division","saison", "journee","club_recevant"="club")) %>% 
  mutate(points_recevant = points) %>% 
  select(-c(match_joue, total_point, points))

df2 <- df2 %>% 
  left_join(point_jour_final, by = c("HF","division","saison", "journee","club_visiteur"="club")) %>% 
  mutate(points_visiteur = points) %>% 
  select(-c(match_joue, total_point, points))

df2 <- df2 %>% 
  mutate (diff_point = points_recevant - points_visiteur)

df2 <- df2 %>%
  group_by(saison, division, HF, journee) %>%
  mutate(diff_point_norm = as.numeric(scale(diff_point))) %>%
  ungroup()


for (i in 1:nrow(df)){
  df2$diff_point_norm[i] <- ifelse (df2$diff_point[i] == 0, 0, df2$diff_point_norm[i])
}

df2 <- df2 %>% select(saison, division, HF, journee, code_rencontre, diff_point, diff_point_norm)

write.csv(df2, "Data/data_diff_point_norme_N1_2.csv")

```


# Graphes

```{r}
df2 <- read.csv("Data/data_diff_point_norme_N1.csv", row.names = 1)

df2 %>% 
  na.omit() %>% 
  mutate(journee_num = as.numeric(str_extract(journee, "[0-9].*")) )%>% 
  ggplot(aes(x = journee_num, y = diff_point)) +
  geom_point(color = "blue", size = 2, alpha = 0.7) +  # Points bien alignés
  labs(title = "Nuage de points des différences de points par journée",
       x = "Journée",
       y = "Différence de points") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))



df_ref_point <- df2 %>% group_by(saison, division, HF, journee) %>% 
  summarise(ref_diff_point1 = sd(diff_point, na.rm = TRUE) + mean(diff_point, na.rm = TRUE), .groups = "drop")


df_ref_point <- df_ref_point %>%  na.omit()
clustering <- kmeans(df_ref_point$ref_diff_point1, centers = 3)
df_ref_point$group_diff_point <- factor(clustering$cluster, levels = c(3,1,2))

table(df_ref_point$group_diff_point)

df_ref_point <- df_ref_point %>% 
  mutate(ecart_classement = case_when(
    group_diff_point == 3 ~ "faible",
    group_diff_point == 1 ~ "moyen",
    group_diff_point == 2 ~ "eleve"
  ))

df_ref_point$ecart_classement <- factor(df_ref_point$ecart_classement, levels = c("faible","moyen","eleve"))

df_ref_point %>% 
  mutate(journee_num = as.numeric(str_extract(journee, "[0-9].*"))) %>% 
  ggplot(aes(x = journee_num, y = ref_diff_point1, color = ecart_classement)) +  # Ajout de 'color = group_diff_point'
  geom_point(size = 2, alpha = 0.7) +  # Points bien alignés
  labs(title = "Nuage de points des différences de points pour 1 point normé par journée",
       x = "Journée",
       y = "Différence de points") +
  scale_x_continuous(breaks = seq(0, 30, by = 2)) +
  theme_minimal()
  #geom_smooth()
```

# Graphe répartition de diff_point_norm

```{r}
data_mod1 %>% 
  ggplot(aes(x = diff_point_norm)) +
  geom_density() +
  theme_minimal()
```

# Mettre variable diff_point_norm en catégorielle

```{r}
data_mod1$abs_diff_point_norm <- abs(data_mod1$diff_point_norm)
clustering <- kmeans(data_mod1$abs_diff_point_norm, centers = 3)
data_mod1$group_diff_point <- as.factor(clustering$cluster)

table(data_mod1$group_diff_point)

ggplot(data_mod1, aes(x = group_diff_point, y = abs_diff_point_norm, fill = group_diff_point)) +
  geom_boxplot() +
  labs(title = "Répartition des groupes créés", x = "Groupes", y = "Valeurs de A") +
  theme_minimal()

data_mod1 %>% 
  mutate(journee_num = as.numeric(str_extract(journee, "[0-9].*")) )%>% 
  ggplot(aes(x = journee_num, y = diff_point, color = group_diff_point)) +
  geom_point(size = 2, alpha = 0.7) +  # Points bien alignés
  labs(title = "Nuage de points des différences de points par journée",
       x = "Journée",
       y = "Différence de points") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```








