---
title: "Modèles statistiques"
author: "Marine"
date: "2024-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Importations

```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(stringr)
library(ggplot2)
```

# Modèle 1 

## Préparation du jeu de données 

```{r}
data <- read.table("df_pdfs.csv", header = TRUE, sep = ",")

classement_D1H_2425 <- read.table("classement_D1H_2425.csv", header = TRUE, sep = ",")
classement_D1H_2324 <- read.table("classement_D1H_2324.csv", header = TRUE, sep = ",")
classement_D1F_2425 <- read.table("classement_D1F_2425.csv", header = TRUE, sep = ",")
classement_D1F_2324 <- read.table("classement_D1F_2324.csv", header = TRUE, sep = ",")
classement_D2H_2425 <- read.table("classement_D2H_2425.csv", header = TRUE, sep = ",")
classement_D2H_2324 <- read.table("classement_D2H_2324.csv", header = TRUE, sep = ",")
classement_D2F_2425 <- read.table("classement_D2F_2425.csv", header = TRUE, sep = ",")
classement_D2F_2324 <- read.table("classement_D2F_2324.csv", header = TRUE, sep = ",")

classement_D1H_2425$division <- "D1"
classement_D1H_2425$saison <- "2425"
classement_D1H_2425$HF <- "H"

classement_D1H_2324$division <- "D1"
classement_D1H_2324$saison <- "2324"
classement_D1H_2324$HF <- "H"

classement_D1F_2425$division <- "D1"
classement_D1F_2425$saison <- "2425"
classement_D1F_2425$HF <- "F"

classement_D1F_2324$division <- "D1"
classement_D1F_2324$saison <- "2324"
classement_D1F_2324$HF <- "F"

classement_D2H_2425$division <- "D2"
classement_D2H_2425$saison <- "2425"
classement_D2H_2425$HF <- "H"

classement_D2H_2324$division <- "D2"
classement_D2H_2324$saison <- "2324"
classement_D2H_2324$HF <- "H"

classement_D2F_2425$division <- "D2"
classement_D2F_2425$saison <- "2425"
classement_D2F_2425$HF <- "F"

classement_D2F_2324$division <- "D2"
classement_D2F_2324$saison <- "2324"
classement_D2F_2324$HF <- "F"

classements <- bind_rows(classement_D1H_2425, 
                         classement_D1H_2324,
                         classement_D1F_2425,
                         classement_D1F_2324,
                         classement_D2H_2425,
                         classement_D2H_2324,
                         classement_D2F_2425,
                         classement_D2F_2324)

data <- data %>%
  separate(score_final, into = c("score_final_r", "score_final_v"), sep = "-") %>%
  mutate(
    score_final_r = as.integer(score_final_r),
    score_final_v = as.integer(score_final_v)
  )

data_mod1 <- data %>%
  filter(abs(score_final_r - score_final_v) <= 3) %>%
  group_by(code_rencontre, club_recevant, coach_recevant, club_visiteur, coach_visiteur, score_final_r, score_final_v, fichier) %>%
  summarise(temps_proche_59_min = max(Temps_Sec[Temps_Sec < 59 * 60], na.rm = TRUE),
            statut_59_min_r = first(statut_recevant[Temps_Sec == temps_proche_59_min]),
            statut_59_min_v = -statut_59_min_r,
            score_recevant_59_min = first(score_recevant[Temps_Sec == temps_proche_59_min]),
            score_visiteur_59_min = first(score_visiteur[Temps_Sec == temps_proche_59_min]),
            TM_derniere_min_r = if_else(
              any(Temps_Sec >= 59 * 60 & grepl("tem", action, ignore.case = TRUE) & action_equipe == "r"),
              1, 
              0
              ),
            TM_derniere_min_v = if_else(
              any(Temps_Sec >= 59 * 60 & grepl("tem", action, ignore.case = TRUE) & action_equipe == "v"),
              1, 
              0
              ),
            DM_r = if_else(
              any(Temps_Sec >= 58 * 60 & (grepl("2MN", action, ignore.case = TRUE) | grepl("Dis", action, ignore.case = TRUE)) & action_equipe == "r"),
              1, 
              0
              ),
            DM_v = if_else(
              any(Temps_Sec >= 58 * 60 & (grepl("2MN", action, ignore.case = TRUE) | grepl("Dis", action, ignore.case = TRUE)) & action_equipe == "v"),
              1, 
              0
              )
            ) %>%
  pivot_longer(
    cols = c(statut_59_min_r, statut_59_min_v), 
    names_to = "equipe", 
    values_to = "statut_59_min"
  ) %>%
  mutate(
    equipe = case_when(
      equipe == "statut_59_min_r" ~ "R",
      equipe == "statut_59_min_v" ~ "V"
    ),
    statut_final = case_when(
      equipe == "R" & score_final_r > score_final_v ~ 1,
      equipe == "V" & score_final_v > score_final_r ~ 1,
      score_final_v == score_final_r ~ 0,
      equipe == "R" & score_final_r < score_final_v ~ -1,
      equipe == "V" & score_final_v < score_final_r ~ -1,
    ),
    effet_positif = case_when(
      statut_59_min == -1 & (statut_final == 0 | statut_final == 1) ~ 1,
      statut_59_min == 1 & statut_final == 1 ~ 1,
      statut_59_min == 0 & statut_final == 1 ~ 1,
      TRUE ~ 0
    ),
    TM_derniere_min = case_when(
      equipe == "R" & TM_derniere_min_r == 1 ~ 1,
      equipe == "V" & TM_derniere_min_v == 1 ~ 1,
      TRUE ~ 0
    ),
    HF = case_when(
      grepl("D1F", fichier, ignore.case = TRUE) | grepl("D2F", fichier, ignore.case = TRUE) ~ "F",
      TRUE ~ "H"
    ),
    DM_adverse = case_when(
      equipe == "V" & DM_r == 1 ~ 1,
      equipe == "R" & DM_v == 1 ~ 1,
      TRUE ~ 0
    ),
    division = case_when(
      grepl("D1", fichier, ignore.case = TRUE) ~ "D1",
      grepl("D2", fichier, ignore.case = TRUE) ~ "D2"
    ),
    saison = case_when(
      grepl("2425", fichier, ignore.case = TRUE) ~ "2425",
      grepl("2324", fichier, ignore.case = TRUE) ~ "2324"
    )
  ) %>% 
  select(-c(TM_derniere_min_r, TM_derniere_min_v, DM_r, DM_v, temps_proche_59_min))

classements <- classements %>%
  mutate(Club = str_to_lower(str_trim(Club))) 

data_mod1 <- data_mod1 %>%
  mutate(club_ref = case_when(equipe == "R" ~ club_recevant, equipe == "V" ~ club_visiteur)) %>%
  mutate(club_ref = str_to_lower(str_trim(club_ref))) %>% 
  mutate(club_opp = case_when(equipe == "R" ~ club_visiteur, equipe == "V" ~ club_recevant)) %>%
  mutate(club_opp = str_to_lower(str_trim(club_opp))) %>%
  left_join(
    classements[, -c(3:10)],
    by = c(
      "division" = "division",
      "saison" = "saison",
      "HF" = "HF",
      "club_ref" = "Club"
    )
  ) %>%
  mutate(pos_classement = Pos.) %>%
  select(-c(Pos.)) %>%
  left_join(
    classements[, -c(3:10)],
    by = c(
      "division" = "division",
      "saison" = "saison",
      "HF" = "HF",
      "club_opp" = "Club"
    )
  ) %>%
  mutate(pos_opp = Pos.) %>%
  select(-c(Pos.)) 

clubs <- data.frame(feuille_match = c(unique(data_mod1$club_ref[is.na(data_mod1$pos_classement)])),
                    classement = c("js cherbourgeoise  manche hb",
                                   "provence aix universite club handball",
                                   "limoges hand 87",
                                   "paris 92",
                                   "st amand handball -  porte du hainaut",
                                   "handball clermont auvergne metropole 63",
                                   "bouillargues handball nimes mediterranee",
                                   "le pouzin hb 07",
                                   "cherbourg js manche hb"
                                  ))

data_mod1 <- data_mod1 %>%
  left_join(
    clubs %>% select(feuille_match, classement),
    by = c("club_ref" = "feuille_match")
  ) %>%
  mutate(
    club_ref = if_else(!is.na(classement), classement, club_ref)
  ) %>%
  select(-classement) 

data_mod1 <- data_mod1 %>%
  left_join(
    classements[, -c(3:10)],
    by = c(
      "division" = "division",
      "saison" = "saison",
      "HF" = "HF",
      "club_ref" = "Club"
    )
  ) %>%
  mutate(pos_classement = Pos.) %>%
  select(-Pos.)

data_mod1 <- data_mod1 %>%
  left_join(
    clubs %>% select(feuille_match, classement),
    by = c("club_opp" = "feuille_match")
  ) %>%
  mutate(
    club_opp = if_else(!is.na(classement), classement, club_opp)
  ) %>%
  select(-classement) 

data_mod1 <- data_mod1 %>%
  left_join(
    classements[, -c(3:10)],
    by = c(
      "division" = "division",
      "saison" = "saison",
      "HF" = "HF",
      "club_opp" = "Club"
    )
  ) %>%
  mutate(pos_opp = Pos.) %>%
  select(-c(Pos., club_ref, club_opp)) %>% 
  mutate(diff_classement = pos_opp - pos_classement)
  

```

## distribution des variables

```{r}

# Graphique pour effet_positif
ggplot(data.frame(Var = names(table(data_mod1$effet_positif)), 
                  Freq = as.numeric(table(data_mod1$effet_positif))), aes(x = Var, y = Freq, fill = Var)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = Freq), vjust = -0.5) +
  labs(title = "Distribution de effet_positif", x = "Effet positif", y = "Fréquence") +
  scale_fill_manual(values = c("red", "green3")) +
  theme_minimal() +
  theme(legend.position = "none")

# Graphique pour TM_derniere_min
ggplot(data.frame(Var = names(table(data_mod1$TM_derniere_min)), 
                  Freq = as.numeric(table(data_mod1$TM_derniere_min))), aes(x = Var, y = Freq, fill = Var)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = Freq), vjust = -0.5) +
  labs(title = "Distribution de TM_derniere_min", x = "Temps mort à la dernière minute", y = "Fréquence") +
  scale_fill_manual(values = c("skyblue", "orange")) +
  theme_minimal() +
  theme(legend.position = "none")

# Graphique pour HF
ggplot(data.frame(Var = names(table(data_mod1$HF)), 
                  Freq = as.numeric(table(data_mod1$HF))), aes(x = Var, y = Freq, fill = Var)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = Freq), vjust = -0.5) +
  labs(title = "Distribution de HF", x = "Hommes ou femmes", y = "Fréquence") +
  scale_fill_manual(values = c("skyblue", "orange")) +
  theme_minimal() +
  theme(legend.position = "none")

# Graphique pour DM_adverse
ggplot(data.frame(Var = names(table(data_mod1$DM_adverse)), 
                  Freq = as.numeric(table(data_mod1$DM_adverse))), aes(x = Var, y = Freq, fill = Var)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = Freq), vjust = -0.5) +
  labs(title = "Distribution de DM_adverse", x = "2min de l'adversaire", y = "Fréquence") +
  scale_fill_manual(values = c("skyblue", "orange")) +
  theme_minimal() +
  theme(legend.position = "none")

hist(data_mod1$diff_classement)

```



## Modèle 1

```{r}

data_mod1$effet_positif <- as.factor(data_mod1$effet_positif)
data_mod1$TM_derniere_min <- as.factor(data_mod1$TM_derniere_min)
data_mod1$HF <- as.factor(data_mod1$HF)
data_mod1$equipe <- as.factor(data_mod1$equipe)
data_mod1$DM_adverse <- as.factor(data_mod1$DM_adverse)

mod1 <- glm(effet_positif ~ TM_derniere_min + HF + equipe + diff_classement + DM_adverse, data = data_mod1, family = "binomial")
summary(mod1)

```





