---
title: "Stat Descriptive"
author: "Amélie Brejot"
date: "2024-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(ggplot2)
library(dplyr)
library(ggpubr)
library(tidyr)
library(stringr)
```

```{r}
df <- read.csv("../Data/df_pdfs.csv", stringsAsFactors = T)

colnames(df)
```

```{r}
str(df)
df$statut_recevant <- as.factor(df$statut_recevant)

```

# Regrouper par période
```{r}
data <- df %>%
  group_by(fichier) %>%
  mutate(
    periode = case_when(
      Temps_Sec >= 0 & Temps_Sec < 600 ~ 1,  # 0 - 10 minutes
      Temps_Sec >= 600 & Temps_Sec < 1200 ~ 2,  # 10 - 20 minutes
      Temps_Sec >= 1200 & Temps_Sec < 1800 ~ 3,  # 20 - 30 minutes
      Temps_Sec >= 1800 & Temps_Sec < 2400 ~ 4,  # 30 - 40 minutes
      Temps_Sec >= 2400 & Temps_Sec < 3000 ~ 5,  # 40 - 50 minutes
      Temps_Sec >= 3000 ~ 6,  # 50 - 60 minutes
      TRUE ~ NA_real_  # Valeur par défaut pour les autres cas (au cas où)
    )
  ) %>%
  ungroup()
data$statut_action <- ""
data$statut_action <- with(data,
                       ifelse(action_equipe == "v",
                              # Inverser les valeurs
                              ifelse(as.character(statut_recevant) == "-1", "1",
                                     ifelse(as.character(statut_recevant) == "1", "-1", "0")),
                              # Sinon, garder la valeur d'origine
                              as.character(statut_recevant))
)


```


# Diagramme nombre de but par période et par statut
```{r}
p1 <- ggplot(data = data[data$action == "Tem",], aes(x=as.factor(periode), fill = statut_action)) +
  geom_bar() +
  labs(
    title = "Nombre de temps-mort par période",
    x = "Période (1 période = 10 min)",
    y = "Nombre de Temps-Mort",
    fill = "Statut équipe"
  ) +
  scale_fill_manual(
    values = c("-1" = "indianred", "0" = "gray", "1" = "darkolivegreen3"),
    labels = c("-1"="Perd", "0"="Egalité","1"="Gagne")
  ) +
  theme_minimal()

p2 <- data %>% filter(Temps_Sec >= 59*60) %>% 
  ggplot(aes(x=as.factor(periode), fill = statut_action)) +
  geom_bar() +
  labs(
    title = "Nombre de temps-\nmort à la dernière \nminute",
    x = "Période 59min à 60min (fin)",
    y = "Nombre de Temps-Mort",
    fill = "Statut équipe"
  ) +
  scale_fill_manual(
    values = c("-1" = "indianred", "0" = "gray", "1" = "darkolivegreen3"),
    labels = c("-1"="Perd", "0"="Egalité","1"="Gagne")
  ) +
  theme_minimal()

ggarrange(p1,p2, widths = c(2,1))
```

# Pourcentage de tm pris à la dernière minute ayant mené à un but
```{r}
count_levels <- data %>%
  filter(Temps_Sec >= 59*60, but_1min_apres_temps_mort != "") %>% 
  group_by(but_1min_apres_temps_mort) %>%
  summarise(count = n())

taux_but_ap_tm <- count_levels$count[2] / (count_levels$count[2]+count_levels$count[1])
```

```{r}
levels_but_tir <- data %>% 
  group_by(action) %>% 
  summarise(count=n())

taux_reussite <- levels_but_tir$count[5] / (levels_but_tir$count[5] + levels_but_tir$count[10])
print(c("Taux de réussite : ",round(taux_reussite,2)))

```


# Data 5 min avant/après un temps-mort
```{r}
dt_5min_av <- data %>%
  group_by(code_rencontre) %>%
  mutate(
    temps_tem = list(Temps_Sec[action == "Tem"])
  ) %>%
  unnest(temps_tem) %>% # Transformer les listes en colonnes
  filter(
    Temps_Sec < temps_tem & Temps_Sec >= temps_tem - 5 * 60 & action != "Tem"
  ) %>%
  ungroup()

dt_5min_ap <- data %>%
  group_by(code_rencontre) %>%
  mutate(
    temps_tem = list(Temps_Sec[action == "Tem"])
  ) %>%
  unnest(temps_tem) %>%
  filter(
    Temps_Sec > temps_tem & Temps_Sec <= temps_tem + 5 * 60 & action != "Tem"
  ) %>%
  ungroup()
```

```{r}
count_av <- dt_5min_av %>% 
  group_by(action) %>% 
  summarise(count=n())

nb_but_av <- count_av$count[count_av$action == "But"]
nb_tir_av <- count_av$count[count_av$action == "Tir"]
taux_but_av <- round(nb_but_av / (nb_but_av + nb_tir_av)*100,2)
taux_tir_av <- round(nb_tir_av / (nb_but_av + nb_tir_av)*100,2)

count_ap <- dt_5min_ap %>% 
  group_by(action) %>% 
  summarise(count=n())

nb_but_ap <- count_ap$count[count_ap$action == "But"]
nb_tir_ap <- count_ap$count[count_ap$action == "Tir"]
taux_but_ap <- round(nb_but_ap / (nb_but_ap + nb_tir_ap)*100,2)
taux_tir_ap <- round(nb_tir_ap / (nb_but_ap + nb_tir_ap)*100,2)
```

```{r}
library(knitr)
library(kableExtra)

data2 <- data.frame(
  Category = c("Actions positives", "But", "Actions négatives", "Tir", "Total"),
  N_avant = c("", nb_but_av, "", nb_tir_av, nb_but_av+nb_tir_av),
  Pourc_avant = c("", taux_but_av, "", taux_tir_av, 100),
  #Percent_actions_before = c("", 37.7, "", "", 62.3, "", 100),
  N_apres = c("", nb_but_ap, "", nb_tir_ap, nb_tir_ap+nb_but_ap),
  Pourc_apres = c("", taux_but_ap, "", taux_tir_ap, 100),
  #Percent_actions_after = c("", 46.8, "", "", 53.2, "", 100)
  Comparaison = c("", round(taux_but_ap-taux_but_av,2),"", round(taux_tir_ap-taux_tir_av,2),0)
)

data2 %>%
  kbl(col.names = c("", "N", "%", "N", "%", "ap - av (%)"),
      align = c("l", "c", "c", "c", "c","c")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F) %>%
  add_header_above(c(" " = 1, "Actions 5min avant un temps_mort" = 2, "Actions 5min après un temps-mort" = 2, "Comparaison" = 1)) %>%
  footnote(general = "N: Nombre d'attaques")

```

```{r}

score_moyen_r <- data %>% 
 mutate(
    score_final_r = as.numeric(str_split(score_final, "-", simplify = TRUE)[, 1])
  ) %>% 
  group_by(club_recevant) %>% 
  summarise(score_moyen_r = mean(score_final_r))

score_moyen_v <- data %>% 
 mutate(
    score_final_v = as.numeric(str_split(score_final, "-", simplify = TRUE)[, 2])
  ) %>% 
  group_by(club_recevant) %>% 
  summarise(score_moyen_v = mean(score_final_v))

score_moyen <- score_moyen_r %>% 
  left_join(score_moyen_v, by = "club_recevant") %>% 
  mutate (score_moyen = (score_moyen_r+score_moyen_v)/2, 
          club = club_recevant) %>% 
  select(club, score_moyen) %>% 
  arrange(desc(score_moyen))

```

# Tableau disjonctif entre TM et DM

```{r}
data_mod1 <- read.csv("../Data/data_mod1.csv")

table_disj_tm <- as.data.frame(table(data_mod1$TM_derniere_min, data_mod1$TM_derniere_min_adverse))
table_disj_dm <- as.data.frame(table(data_mod1$DM, data_mod1$DM_adverse))

colnames(table_disj_tm) <- c("tm", "tm_adverse", "count")
colnames(table_disj_dm) <- c("dm", "dm_adverse", "count")

print(table_disj_dm)
print(table_disj_tm)
```

Classement par jour

```{r}
point_jour <- read.csv("../Data/point_jour.csv", header = T, sep = ";", row.names = 1)

point_jour_F <- point_jour %>% filter(HF == 'F') %>% 
  select(-c(J27,J28,J29,J30))
point_jour_H <- point_jour %>% filter(HF == 'H')


# Point par jour de la compétition masculine D1 et D2, 2223 et 2324
for (i in 1:nrow(point_jour_H)){
  if (is.na(point_jour_H$J1[i]) == T){
    point_jour_H$J1[i] <- 0
  }
  for (j in 6:34){  # j = [J2:J6]
    if (is.na(point_jour_H[i,j-1])==T){
      point_jour_H[i,j-1] <- point_jour_H[i,j-2]
      point_jour_H[i,j] <- point_jour_H[i,j] + point_jour_H[i,j-1]
    } else {
      point_jour_H[i,j] <- point_jour_H[i,j] + point_jour_H[i,j-1]
    }
  }
  
  if(is.na(point_jour_H$J30[i])==T){
    point_jour_H$J30[i] <- point_jour_H$J29[i]
  }
}

# Point par jour de la compétition féminine D1 et D2, 2223 et 2324
for (i in 1:nrow(point_jour_F)){
  if (is.na(point_jour_F$J1[i]) == T){
    point_jour_F$J1[i] <- 0
  }
  for (j in 6:30){  # j = [J2:J26]
    if (is.na(point_jour_F[i,j-1])==T){
      point_jour_F[i,j-1] <- point_jour_F[i,j-2]
      point_jour_F[i,j] <- point_jour_F[i,j] + point_jour_F[i,j-1]
    } else {
      point_jour_F[i,j] <- point_jour_F[i,j] + point_jour_F[i,j-1]
    }
  }
  if(is.na(point_jour_F$J26[i])==T){
    point_jour_F$J26[i] <- point_jour_F$J25[i]
  }
  
}


point_jour_F$saison <- factor(point_jour_F$saison)
point_jour_F$division <- factor(point_jour_F$division)

point_jour_H$saison <- factor(point_jour_H$saison)
point_jour_H$division <- factor(point_jour_H$division)

write.csv(point_jour_F, "point_jour_F.csv")
write.csv(point_jour_H, "point_jour_H.csv")
```

Evolution difference de classement par jour

```{r}
##### Evolution difference Femme

summary_df_F <- point_jour_F %>% 
  select(-c("match_joue", "total_point")) %>% 
  group_by(saison, division) %>%
  summarise(across(where(is.numeric), list(Max = max, 
                                           Min = min), 
                   .names = "{.col}_{.fn}")) %>%
  pivot_longer(cols = -c(saison, division), 
               names_to = c("Jour", ".value"), 
               names_pattern = "(.*)_(.*)") %>%  
  mutate (Diff = Max - Min)

summary_df_F$Jour <- factor(summary_df_F$Jour, 
                          levels = unique(summary_df_F$Jour[order(as.numeric(str_extract(summary_df_F$Jour, "\\d+")))]))

ggplot(summary_df_F, aes(x = Jour, group = interaction(saison, division))) +
  geom_line(aes(y = Diff, color = interaction(saison, division))) +
  labs(title = "Évolution dfférence de points entre premier et dernier (F)",
       x = "Journées", y = "Ecarts", color = "Saison-Division") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#### Evolution difference Homme

summary_df_H <- point_jour_H %>% 
  select(-c("match_joue", "total_point")) %>% 
  group_by(saison, division) %>%
  summarise(across(where(is.numeric), list(Max = max, 
                                           Min = min), 
                   .names = "{.col}_{.fn}")) %>%
  pivot_longer(cols = -c(saison, division), 
               names_to = c("Jour", ".value"), 
               names_pattern = "(.*)_(.*)") %>%  
  mutate (Diff = Max - Min)

summary_df_H$Jour <- factor(summary_df_H$Jour, 
                          levels = unique(summary_df_H$Jour[order(as.numeric(str_extract(summary_df_H$Jour, "\\d+")))]))

ggplot(summary_df_H, aes(x = Jour, group = interaction(saison, division))) +
  geom_line(aes(y = Diff, color = interaction(saison, division))) +
  labs(title = "Évolution dfférence de points entre premier et dernier (H)",
       x = "Journées", y = "Ecarts", color = "Saison-Division") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
