---
title: "Data final"
author: "Amélie Brejot"
date: "2025-01-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Imports

```{r}
library(dplyr)
library(readr)
library(tidyverse)
```

# Importation data

```{r}
# data1 <- read.csv("Data/df_pdfs.csv")
# data2 <- read.csv("df_pdfs_N1.csv")
# data3 <- read.csv("df_pdfs_N1_2.csv")
# data4 <- read.csv("df_pdfs_2425.csv")
```


# Assemblage data

```{r}
# data <- rbind(data1, data2) %>% rbind(data3) %>% rbind(data4)
# write.csv(data, "df_pdfs_final.csv")

data <- read.csv("../data_final/df_pdfs_final.csv")
summary(data)
```

# Traitement data

```{r}
data <- data %>%
  separate(score_final, into = c("score_final_r", "score_final_v"), sep = "-") %>%
  mutate(
    score_final_r = as.integer(score_final_r),
    score_final_v = as.integer(score_final_v)
  )

data <- data %>%
  mutate(
    saison = str_extract(fichier, "\\d{4}"),           
    HF = str_extract(fichier, "[FH]"),              
    division = str_extract(fichier, "(D|N)\\d"),          
    match_num = str_extract(fichier, "_\\d+_\\d{4}") %>%
      str_extract("^\\d+")
  ) %>% 
  select(-match_num)

data <- data %>% 
  select("code_rencontre","club_recevant","club_visiteur", "score_final_r", "score_final_v",
                    "division","HF","saison", "journee", "fichier") %>%
  distinct(code_rencontre, .keep_all = TRUE)
# %>%
#   filter(saison != 2425)
```

# Mise ajour nom club

```{r}
data <- data %>% 
  mutate(club_recevant = case_when(
    club_recevant == "BOUILLARGUES HANDBALL NIMES MEDITERRANEE" ~ "BOUILLARGUES HANDBALL NIMES METROPOLE",
    club_recevant == "C'CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
    club_recevant == "NANCY METROPOLE HB" ~ "NANCY METROPOLE",
    club_recevant == "NANCY HANDBALL" ~ "NANCY METROPOLE",
    club_recevant == "PAYS AIX UNIVERSITE CLUB HANDBALL" ~ "PROVENCE AIX UNIVERSITE CLUB HANDBALL",
    club_recevant == "VILLEURBANNE HANDBALL ASSOCIATION" ~ "VILLEURBANNE HANDBALL",
    club_recevant == "TREMBLAY EN FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
    club_recevant == "TREMBLAY-EN-FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
    club_recevant == "TOULON METROPOLE VAR HB" ~ "TOULON METROPOLE VAR HANDBALL",
    club_recevant == "BILLERE HANDBALL" ~ "BILLERE HANDBALL PAU PYRENEES",
    club_recevant == "CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
    club_recevant == "CAVIGAL NICE SPORTS HANDBALL" ~ "CAVIGAL NICE HANDBALL",
    club_recevant == "FRONTIGNAN HANDBALL" ~ "FRONTIGNAN THAU HANDBALL",
    club_recevant == "HBC NANTAIS" ~ "HBC NANTES",
    club_recevant == "MASSY ESSONNE HB" ~ "MASSY ESSONNE HANDBALL",
    club_recevant == "NOISY-LE-GRAND HANDBALL" ~ "NOISY LE GRAND HANDBALL",
    club_recevant == "HBC ST AMAND LES EAUX PORTE DU HAINAUT" ~ "ST AMAND HANDBALL - PORTE DU HAINAUT",
    club_recevant == "CHAMBERY SAVOIE MT-BLANC HB" ~ "CHAMBERY SAVOIE HB",
    club_recevant == "GRAND NANCY METROPOLE HB" ~ "GRAND NANCY METROPOLE HANDBALL",
    club_recevant == "LIMOGES HAND" ~ "LIMOGES HANDBALL",
    club_recevant == "SAINT RAPHAEL VHB" ~ "SAINT RAPHAEL VAR HANDBALL",
    club_recevant == "SARAN LOIRET HB" ~ "SARAN LOIRET HANDBALL",
    club_recevant == "DIJON METROPOLE HB" ~ "DIJON METROPOLE HANDBALL",
    club_recevant == "JS CHERBOURGEOISE MANCHE HB" ~ "JS CHERBOURGEOISE MANCHE HANDBALL",
    club_recevant == "E. STRASBOURG SCHILTIGHEIM ALSACE HANDBALL" ~ "STRASBOURG EUROMETROPOLE HB",
    club_recevant == "LIMOGES HANDBALL" ~ "LIMOGES",
    club_recevant == "LIMOGES HAND" ~ "LIMOGES",
    club_recevant == "ELITE VAL D'OISE" ~ "ELITE VAL-D'OISE",
    club_recevant =="ASSOCIATION SPORTIVE ST-OUEN-L'AUMONE HANDBALL" ~ "ASSOCIATION SPORTIVE ST-OUEN-L'AUMONE",
    club_recevant =="LILLE METROPOLE - HANDBALL CLUB VILLENEUVE D'ASCQ" ~ "LILLE METROPOLE - HANDBALL CLUB",
    club_recevant == "MOntpellier Handball feminin N" ~ "HB FEMININ MONTPELLIER MEDITERRANEE",
    club_recevant == "LES NEPTUNES DE NANTES" ~ "NANTES HANDBALL FEMININ",
    club_recevant == "ISSY-PARIS HAND" ~ "PARIS",
    club_recevant == "AS LYON CALUIRE" ~ "LYON-CALUIRE HANDBALL",
    club_recevant == "JS CHERBOURG MANCHE HB" ~ "CHERBOURG JS MANCHE HB",
    club_recevant == "HBC Nantes" ~ "NANTES HBC",
    club_recevant == "PAU BILLERE HANDBALL PAU PYRENEES" ~ "PAU BILLERE HANDBALL",
    TRUE ~ club_recevant
  )) %>% 
filter (club_recevant != "HBC ST AMAND LES EAUX PORTE DU HAINAUT",club_visiteur != "SAINT-CYR VAR HANDBALL")

data <- data %>% 
  mutate(club_visiteur = case_when(
   club_visiteur == "BOUILLARGUES HANDBALL NIMES MEDITERRANEE" ~ "BOUILLARGUES HANDBALL NIMES METROPOLE",
    club_visiteur == "C'CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
    club_visiteur == "NANCY METROPOLE HB" ~ "NANCY METROPOLE",
    club_visiteur == "NANCY HANDBALL" ~ "NANCY METROPOLE",
    club_visiteur == "PAYS AIX UNIVERSITE CLUB HANDBALL" ~ "PROVENCE AIX UNIVERSITE CLUB HANDBALL",
    club_visiteur == "VILLEURBANNE HANDBALL ASSOCIATION" ~ "VILLEURBANNE HANDBALL",
    club_visiteur == "TREMBLAY EN FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
    club_visiteur == "TREMBLAY-EN-FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
    club_visiteur == "TOULON METROPOLE VAR HB" ~ "TOULON METROPOLE VAR HANDBALL",
    club_visiteur == "BILLERE HANDBALL" ~ "BILLERE HANDBALL PAU PYRENEES",
    club_visiteur == "CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
    club_visiteur == "CAVIGAL NICE SPORTS HANDBALL" ~ "CAVIGAL NICE HANDBALL",
    club_visiteur == "FRONTIGNAN HANDBALL" ~ "FRONTIGNAN THAU HANDBALL",
    club_visiteur == "HBC NANTAIS" ~ "HBC NANTES",
    club_visiteur == "MASSY ESSONNE HB" ~ "MASSY ESSONNE HANDBALL",
    club_visiteur == "NOISY-LE-GRAND HANDBALL" ~ "NOISY LE GRAND HANDBALL",
    club_visiteur == "HBC ST AMAND LES EAUX PORTE DU HAINAUT" ~ "ST AMAND HANDBALL - PORTE DU HAINAUT",
    club_visiteur == "CHAMBERY SAVOIE MT-BLANC HB" ~ "CHAMBERY SAVOIE HB",
    club_visiteur == "GRAND NANCY METROPOLE HB" ~ "GRAND NANCY METROPOLE HANDBALL",
    club_visiteur == "LIMOGES HAND" ~ "LIMOGES HANDBALL",
    club_visiteur == "SAINT RAPHAEL VHB" ~ "SAINT RAPHAEL VAR HANDBALL",
    club_visiteur == "SARAN LOIRET HB" ~ "SARAN LOIRET HANDBALL",
    club_visiteur == "DIJON METROPOLE HB" ~ "DIJON METROPOLE HANDBALL",
    club_visiteur == "JS CHERBOURGEOISE MANCHE HB" ~ "JS CHERBOURGEOISE MANCHE HANDBALL",
    club_visiteur == "E. STRASBOURG SCHILTIGHEIM ALSACE HANDBALL" ~ "STRASBOURG EUROMETROPOLE HB",
    club_visiteur == "LIMOGES HANDBALL" ~ "LIMOGES",
    club_visiteur == "LIMOGES HAND" ~ "LIMOGES",
    club_visiteur == "ELITE VAL D'OISE" ~ "ELITE VAL-D'OISE",
    club_visiteur =="ASSOCIATION SPORTIVE ST-OUEN-L'AUMONE HANDBALL" ~ "ASSOCIATION SPORTIVE ST-OUEN-L'AUMONE",
    club_visiteur =="LILLE METROPOLE - HANDBALL CLUB VILLENEUVE D'ASCQ" ~ "LILLE METROPOLE - HANDBALL CLUB",
    club_visiteur == "MOntpellier Handball feminin N" ~ "HB FEMININ MONTPELLIER MEDITERRANEE",
    club_visiteur == "LES NEPTUNES DE NANTES" ~ "NANTES HANDBALL FEMININ",
    club_visiteur == "ISSY-PARIS HAND" ~ "PARIS",
    club_visiteur == "AS LYON CALUIRE" ~ "LYON-CALUIRE HANDBALL",
    club_visiteur == "JS CHERBOURG MANCHE HB" ~ "CHERBOURG JS MANCHE HB",
    club_visiteur == "HBC Nantes" ~ "NANTES HBC",
    club_visiteur == "PAU BILLERE HANDBALL PAU PYRENEES" ~ "PAU BILLERE HANDBALL",
    TRUE ~ club_visiteur
  )) %>% 
  filter (club_visiteur != "HBC ST AMAND LES EAUX PORTE DU HAINAUT", club_visiteur != "SAINT-CYR VAR HANDBALL" )
```

# Mise en facteur

```{r}
data$division <- as.factor(data$division)
data$HF <- as.factor(data$HF)
data$saison <- as.factor(data$saison)
data$journee <- as.factor(data$journee)
```


# Import data point

```{r}
point_jour1 <- read.csv("Data/point_jour.csv", sep = ";", row.names = 1)
point_jour2 <- read.csv("Data/point_jour_N1.csv",  sep = ";", row.names = 1)
point_jour3 <- read.csv("Data/point_jour_N1_2.csv", sep = ";")
point_jour4 <- read.csv("point_jour_2425.csv", sep = ";", row.names = 1)
```

# Assemblage data point
```{r}
point_jour <- bind_rows(point_jour1, point_jour2) %>%  bind_rows(point_jour3)
```

# Traitement data point

```{r}
for (i in 1:nrow(point_jour)){
  if (is.na(point_jour$J1[i]) == T){
    point_jour$J1[i] <- 0
  }
  for (j in 8:32){  # j = [J2:J6]
    if (is.na(point_jour[i,j-1])==T){
      point_jour[i,j-1] <- point_jour[i,j-2]
      point_jour[i,j] <- point_jour[i,j] + point_jour[i,j-1]
    } else {
      point_jour[i,j] <- point_jour[i,j] + point_jour[i,j-1]
    }
  }
  if(is.na(point_jour$J26[i])==T){
    point_jour$J26[i] <- point_jour$J25[i]
  }
  
}

point_jour$saison <- factor(point_jour$saison)
point_jour$division <- factor(point_jour$division)

point_jour$J0 <- 0
point_jour <- point_jour %>% relocate('J0', .after = 'total_point')

for (j in 32:8){
  point_jour[,j] <- point_jour[,j-1]
}

point_jour <- point_jour %>%
  select(-J0) %>% 
  pivot_longer(cols = starts_with("J"), names_to = "journee", values_to = "points") %>%
  mutate(journee = toupper(journee))

point_jour <- point_jour %>%
  group_by(club) %>%                            
  filter(as.numeric(sub("J", "", journee)) <= match_joue + 2) %>% # prend en compte que certaine équipe ne font que 24 match sur une saison de 26 par exemple
  ungroup() %>% 
  na.omit()

point_jour <- point_jour %>% 
  mutate(club = case_when(
    club == "LIMOGES" ~ "LIMOGES HAND",
    club == "LIMOGES HANDBALL" ~ "LIMOGES HAND",
    TRUE ~ club
  ))

write.csv(point_jour, "../data_final/point_jour_final.csv")
```


# Ajout diff_point_norm

```{r}
point_jour <- read.csv("../data_final/point_jour_final.csv")

data_point <- data %>% 
  left_join(point_jour, by = c("HF","division","saison", "journee","club_recevant"="club")) %>% 
  mutate(points_recevant = points) %>% 
  select(-c(match_joue, total_point, points))

data_point <- data_point %>% 
  left_join(point_jour, by = c("HF","division","saison", "journee","club_visiteur"="club")) %>% 
  mutate(points_visiteur = points) %>% 
  select(-c(match_joue, total_point, points))

data_point <- data_point %>% 
  mutate (diff_point = points_recevant - points_visiteur)

data_point <- data_point %>%
  group_by(saison, division, HF, journee) %>%
  mutate(diff_point_norm = as.numeric(scale(diff_point))) %>%
  ungroup()


for (i in 1:nrow(data_point)){
  data_point$diff_point_norm[i] <- ifelse (data_point$diff_point[i] == 0, 0, data_point$diff_point_norm[i])
}

data_diff_norme <- data_point %>%
  select(saison, division, HF, journee, code_rencontre, diff_point, diff_point_norm) %>% 
  na.omit()
```

# Enregistrement data_diff_point_norme

```{r}
write.csv(data_diff_norme, "data_diff_norme_final.csv")
```

