---
title: "Modèles à 29 minutes v2"
author: "Amélie Brejot"
date: "2024-12-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Import

```{r}
library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(RcmdrMisc)
library(GGally)
```

# Import données

```{r}
data <- read.csv("../data_final/df_pdfs_final.csv", header = TRUE, sep = ",")
```

# Préparation données

```{r}
data <- data %>%
  separate(score_final, into = c("score_final_r", "score_final_v"), sep = "-") %>%
  mutate(
    score_final_r = as.integer(score_final_r),
    score_final_v = as.integer(score_final_v)
  )

data_mod2 <- data %>%
  group_by(code_rencontre) %>%
  filter(any(Temps_Sec < 29 * 60)) %>%
  ungroup() %>% 
  group_by(code_rencontre, club_recevant, coach_recevant, club_visiteur, coach_visiteur, journee, score_final_r, score_final_v, fichier) %>%
  summarise(temps_proche_29_min = max(Temps_Sec[Temps_Sec < 29 * 60], na.rm = TRUE),
            statut_29_min_r = first(statut_recevant[Temps_Sec == temps_proche_29_min]),
            statut_29_min_v = -statut_29_min_r,
            score_recevant_29_min = first(score_recevant[Temps_Sec == temps_proche_29_min]),
            score_visiteur_29_min = first(score_visiteur[Temps_Sec == temps_proche_29_min]),
            temps_proche_30_min = max(Temps_Sec[Temps_Sec < 30 * 60], na.rm = TRUE),
            statut_30_min_r = first(statut_recevant[Temps_Sec == temps_proche_30_min]),
            statut_30_min_v = -statut_30_min_r,
            score_recevant_30_min = first(score_recevant[Temps_Sec == temps_proche_30_min]),
            score_visiteur_30_min = first(score_visiteur[Temps_Sec == temps_proche_30_min]),
            TM_derniere_min_r = if_else(
              any(Temps_Sec >= 29 * 60 & Temps_Sec <= 30 * 60 & grepl("tem", action, ignore.case = TRUE) & action_equipe == "r"),
              1, 
              0
              ),
            TM_derniere_min_v = if_else(
              any(Temps_Sec >= 29 * 60 & Temps_Sec <= 30 * 60 & grepl("tem", action, ignore.case = TRUE) & action_equipe == "v"),
              1, 
              0
              ),
            DM_r = if_else(
              any(Temps_Sec >= 27 * 60 & Temps_Sec <= 30 * 60 & (grepl("2MN", action, ignore.case = TRUE) | grepl("Dis", action, ignore.case = TRUE)) & action_equipe == "r"),
              1, 
              0
              ),
            DM_v = if_else(
              any(Temps_Sec >= 27 * 60 & Temps_Sec <= 30 * 60 & (grepl("2MN", action, ignore.case = TRUE) | grepl("Dis", action, ignore.case = TRUE)) & action_equipe == "v"),
              1, 
              0
              ), 
            .groups = "drop"
            ) %>%
  filter(abs(score_recevant_29_min - score_visiteur_29_min) <= 3) %>% 
  pivot_longer(
    cols = c(statut_29_min_r, statut_29_min_v), 
    names_to = "equipe", 
    values_to = "statut_29_min"
  ) %>%
  mutate(
    equipe = case_when(
      equipe == "statut_29_min_r" ~ "R",
      equipe == "statut_29_min_v" ~ "V",
    ),
    statut_30_min = case_when(
      equipe == "R" ~ statut_30_min_r,
      equipe == "V" ~ statut_30_min_v,
    ),
    statut_final = case_when(
      equipe == "R" & score_final_r > score_final_v ~ 1,
      equipe == "V" & score_final_v > score_final_r ~ 1,
      score_final_v == score_final_r ~ 0,
      equipe == "R" & score_final_r < score_final_v ~ -1,
      equipe == "V" & score_final_v < score_final_r ~ -1,
    ),
    effet_positif = case_when(
      statut_29_min == -1 & (statut_30_min == 0 | statut_30_min == 1) ~ 1,
      statut_29_min == 1 & statut_30_min == 1 ~ 1,
      statut_29_min == 0 & statut_30_min == 1 ~ 1,
      TRUE ~ 0
    ),
    TM_derniere_min = case_when(
      equipe == "R" & TM_derniere_min_r == 1 ~ 1,
      equipe == "V" & TM_derniere_min_v == 1 ~ 1,
      TRUE ~ 0
    ),
    TM_derniere_min_adverse = case_when(
      equipe == "V" & TM_derniere_min_r == 1 ~ 1,
      equipe == "R" & TM_derniere_min_v == 1 ~ 1,
      TRUE ~ 0
    ),
    HF = case_when(
      grepl("F", fichier) ~ "F",
      TRUE ~ "H"
    ),
     DM = case_when(
      equipe == "R" & DM_r == 1 ~ 1,
      equipe == "V" & DM_v == 1 ~ 1,
      TRUE ~ 0
    ),
    DM_adverse = case_when(
      equipe == "V" & DM_r == 1 ~ 1,
      equipe == "R" & DM_v == 1 ~ 1,
      TRUE ~ 0
    ),
    division = case_when(
      grepl("D1", fichier, ignore.case = TRUE) ~ "D1",
      grepl("D2", fichier, ignore.case = TRUE) ~ "D2",
      grepl("N1", fichier, ignore.case = TRUE) ~ "N1"
    ),
    saison = case_when(
      grepl("2021", fichier, ignore.case = TRUE) ~ "2021",
      grepl("2122", fichier, ignore.case = TRUE) ~ "2122",
      grepl("2223", fichier, ignore.case = TRUE) ~ "2223",
      grepl("2324", fichier, ignore.case = TRUE) ~ "2324",
      grepl("2425", fichier, ignore.case = TRUE) ~ "2425"
    )
  ) %>% 
  dplyr::select(-c(TM_derniere_min_r, TM_derniere_min_v, DM_r, DM_v, temps_proche_29_min, statut_30_min_r, statut_30_min_v))  %>% 
  ungroup() %>% 
  filter (saison != 2425)

# On ne garde que l'équipe recevante 
data_mod2 <- data_mod2 %>%
  filter(equipe == "R") %>% 
  filter(statut_29_min != 0 | statut_30_min != 0)

```

# Mise en facteur

```{r}
data_mod2$statut_29_min <- factor(data_mod2$statut_29_min)
data_mod2$statut_30_min <- factor(data_mod2$statut_30_min)
data_mod2$statut_final <- factor(data_mod2$statut_final)
data_mod2$effet_positif <- factor(data_mod2$effet_positif)
data_mod2$TM_derniere_min <- factor(data_mod2$TM_derniere_min)
data_mod2$TM_derniere_min_adverse <- factor(data_mod2$TM_derniere_min_adverse)
data_mod2$HF <- factor(data_mod2$HF)
data_mod2$DM <- factor(data_mod2$DM)
data_mod2$DM_adverse <- factor(data_mod2$DM_adverse)
data_mod2$club_recevant <- factor(data_mod2$club_recevant)
data_mod2$division <- factor(data_mod2$division)
data_mod2$saison <- factor(data_mod2$saison)
```

# Ajout de la variable différence de point

```{r}
diff_norme <- read.csv("../data_final/data_diff_norme_final.csv", row.names = 1)
diff_norme$saison <- factor(diff_norme$saison)

data_mod2 <- data_mod2 %>% 
  select(-c("journee","division","HF", "saison")) %>% 
  left_join(diff_norme, by = join_by(code_rencontre)) %>% 
  drop_na()
```

```{r}
data_mod2 %>% 
  ggplot(aes(x = diff_point_norm)) +
  geom_density() +
  theme_minimal()

quantiles <- quantile(data_mod2$diff_point_norm, probs = c(0, 1/3, 2/3, 1))

print(quantiles)

data_mod2$group_diff_point <- cut(data_mod2$diff_point_norm,
                                  breaks = quantiles,
                                  labels = c("moins fort","meme niveau","plus fort"),
                                  include.lowest = T)


ggplot(data_mod2, aes(x = group_diff_point, y = diff_point_norm, fill = group_diff_point)) +
  geom_boxplot() +
  labs(title = "Répartition des groupes créés", x = "Groupes", y = "Valeurs de A") +
  theme_minimal()

data_mod2 <- data_mod2 %>% 
  mutate(ecart_classement = case_when(
    group_diff_point == "moins fort" ~ -1,
    group_diff_point == "meme niveau" ~ 0,
    group_diff_point == "plus fort" ~ 1
  ))

data_mod2$ecart_classement <- as.factor(data_mod2$ecart_classement)

data_mod2 %>% 
  mutate(journee_num = as.numeric(str_extract(journee, "[0-9].*")) )%>% 
  ggplot(aes(x = journee_num, y = diff_point_norm, color = group_diff_point)) +
  geom_point(size = 2, alpha = 0.7) +  # Points bien alignés
  labs(title = "Nuage de points des différences de points par journée",
       x = "Journée",
       y = "Différence de points normée") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


# Analyse descriptive

```{r}
# Graphique pour effet_positif
ggplot(data.frame(Var = names(table(data_mod2$effet_positif)), 
                  Freq = as.numeric(table(data_mod2$effet_positif))), aes(x = Var, y = Freq, fill = Var)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = Freq), vjust = -0.5) +
  labs(title = "Distribution de effet_positif", x = "Effet positif", y = "Fréquence") +
  scale_fill_manual(values = c("red", "green3")) +
  theme_minimal() +
  theme(legend.position = "none")

# Graphique pour TM_derniere_min
ggplot(data.frame(Var = names(table(data_mod2$TM_derniere_min_adverse)), 
                  Freq = as.numeric(table(data_mod2$TM_derniere_min_adverse))), aes(x = Var, y = Freq, fill = Var)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = Freq), vjust = -0.5) +
  labs(title = "Distribution de TM_derniere_min", x = "Temps mort à la dernière minute", y = "Fréquence") +
  scale_fill_manual(values = c("skyblue", "orange")) +
  theme_minimal() +
  theme(legend.position = "none")

# Graphique pour HF
ggplot(data.frame(Var = names(table(data_mod2$HF)), 
                  Freq = as.numeric(table(data_mod2$HF))), aes(x = Var, y = Freq, fill = Var)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = Freq), vjust = -0.5) +
  labs(title = "Distribution de HF", x = "Hommes ou femmes", y = "Fréquence") +
  scale_fill_manual(values = c("skyblue", "orange")) +
  theme_minimal() +
  theme(legend.position = "none")

# Graphique pour DM_adverse
ggplot(data.frame(Var = names(table(data_mod2$DM_adverse)), 
                  Freq = as.numeric(table(data_mod2$DM_adverse))), aes(x = Var, y = Freq, fill = Var)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = Freq), vjust = -0.5) +
  labs(title = "Distribution de DM_adverse", x = "2min de l'adversaire", y = "Fréquence") +
  scale_fill_manual(values = c("skyblue", "orange")) +
  theme_minimal() +
  theme(legend.position = "none")

# Graphique statut à 29 minute
df <- data_mod2 %>% filter(HF == 'H')
ggplot(data.frame(Var = names(table(df$statut_29_min)), 
                  Freq = as.numeric(table(df$statut_29_min))), aes(x = Var, y = Freq, fill = Var)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = Freq), vjust = -0.5) +
  labs(title = "Distribution du statut à 29 min", x = "Statut à 29 min", y = "Fréquence") +
  scale_fill_manual(values = c("brown1", "grey", "lightgreen")) +
  theme_minimal() +
  theme(legend.position = "none")

# Graphique répartition écart de classement

ggplot(data.frame(Var = factor(names(table(data_mod2$group_diff_point)), levels = c("moins fort","meme niveau","plus fort")), 
                  Freq = as.numeric(table(data_mod2$group_diff_point))), aes(x = Var, y = Freq, fill = Var)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = Freq), vjust = -0.5) +
  labs(title = "Distribution ecart classement", x = "Ecart classement", y = "Fréquence") +
  scale_fill_manual(values = c("brown1", "grey", "lightgreen")) +
  theme_minimal() +
  theme(legend.position = "none")
```

# Contrastes

```{r}
# contrasts(data_mod2$ecart_classement) <- contr.sum(nlevels(data_mod2$ecart_classement))
data_mod2$ecart_classement <- relevel(data_mod2$ecart_classement, ref = 2)
```



# Modèle global

```{r}
mod2 <- glm(effet_positif ~ TM_derniere_min + TM_derniere_min_adverse + club_recevant + DM_adverse + DM + ecart_classement, data = data_mod2, family = "binomial")
#summary(mod2)

mod_final <- stepwise(mod2, direction = "backward/forward", criterion = "AIC")
mod_final
```

# Modèle égalité

```{r}
data_mod2_egalite <- data_mod2 %>% 
  filter(statut_29_min == 0)

mod2 <- glm(effet_positif ~ TM_derniere_min + TM_derniere_min_adverse + club_recevant + DM_adverse + DM + ecart_classement, data = data_mod2_egalite, family = "binomial")
#summary(mod2)

mod_final_egalite <- stepwise(mod2, direction = "backward/forward", criterion = "AIC")
mod_final_egalite
```

# Modèle perdant

```{r}
data_mod2_perdant <- data_mod2 %>% 
  filter(statut_29_min == -1)

mod2 <- glm(effet_positif ~ TM_derniere_min + TM_derniere_min_adverse + club_recevant + DM_adverse + DM + ecart_classement, data = data_mod2_perdant, family = "binomial")
summary(mod2)

mod_final_perdant <- stepwise(mod2, direction = "backward/forward", criterion = "AIC")
mod_final_perdant
```

# Modèle gagnant

```{r}
data_mod2_gagnant <- data_mod2 %>% 
  filter(statut_29_min == 1)

mod2 <- glm(effet_positif ~ TM_derniere_min + TM_derniere_min_adverse + club_recevant + DM_adverse + DM + ecart_classement, data = data_mod2_gagnant, family = "binomial")
summary(mod2)

mod_final_gagnant <- stepwise(mod2, direction = "backward/forward", criterion = "AIC")
mod_final_gagnant
```


```{r}
ggcoef_compare(list(mod_final,mod_final_egalite, mod_final_perdant, mod_final_gagnant), exponentiate = TRUE, type = "faceted")

pdf("modele_29.pdf", width = 10, height = 7)
ggcoef_compare(
  list(
    "Modèle global" = mod_final,
    "Modèle égalité" = mod_final_egalite,
    "Modèle perdant" = mod_final_perdant,
    "Modèle gagnant" = mod_final_gagnant
  ),
  type = "faceted"
) +
  coord_cartesian(xlim = c(-1.5,1.5)) +  # Limiter l'axe des abscisses
  scale_x_continuous(
    breaks = seq(-1.5,1.5, by = 1),     # Ajouter des ticks tous les 1
    minor_breaks = seq(-1.5,1.5, by = 0.5)  # Sous-ticks tous les 0.5
  )  +
  theme(
    panel.grid.major.x = element_line(color = "grey80", linetype = "longdash"),
    panel.grid.minor.x = element_line(color = "grey90", linetype = "longdash") # Ajouter les lignes pointillées pour les sous-ticks
  )
dev.off()
```
