---
title: "Modele15"
author: "Marine"
date: "2024-12-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Importations

```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(stringr)
library(broom)
library(RcmdrMisc)
library(pls)
```

```{r}

data <- read.table("Data/df_pdfs.csv", header = TRUE, sep = ",")

data <- data %>%
  separate(score_final, into = c("score_final_r", "score_final_v"), sep = "-") %>%
  mutate(
    score_final_r = as.integer(score_final_r),
    score_final_v = as.integer(score_final_v)
  )

data_mod3 <- data %>%
  group_by(code_rencontre) %>%
  filter(any(Temps_Sec < 15 * 60)) %>%
  ungroup() %>% 
  group_by(code_rencontre, club_recevant, coach_recevant, club_visiteur, coach_visiteur, score_final_r, score_final_v, fichier) %>%
  summarise(temps_proche_15_min = max(Temps_Sec[Temps_Sec < 15 * 60], na.rm = TRUE),
            statut_15_min_r = first(statut_recevant[Temps_Sec == temps_proche_15_min]),
            statut_15_min_v = -statut_15_min_r,
            score_recevant_15_min = first(score_recevant[Temps_Sec == temps_proche_15_min]),
            score_visiteur_15_min = first(score_visiteur[Temps_Sec == temps_proche_15_min]),
            temps_proche_16_min = max(Temps_Sec[Temps_Sec < 16 * 60], na.rm = TRUE),
            statut_16_min_r = first(statut_recevant[Temps_Sec == temps_proche_16_min]),
            statut_16_min_v = -statut_16_min_r,
            score_recevant_16_min = first(score_recevant[Temps_Sec == temps_proche_16_min]),
            score_visiteur_16_min = first(score_visiteur[Temps_Sec == temps_proche_16_min]),
            TM_derniere_min_r = if_else(
              any(Temps_Sec >= 15 * 60 & Temps_Sec <= 16 * 60 & grepl("tem", action, ignore.case = TRUE) & action_equipe == "r"),
              1, 
              0
              ),
            TM_derniere_min_v = if_else(
              any(Temps_Sec >= 15 * 60 & Temps_Sec <= 16 * 60 & grepl("tem", action, ignore.case = TRUE) & action_equipe == "v"),
              1, 
              0
              ),
            DM_r = if_else(
              any(Temps_Sec >= 13 * 60 & Temps_Sec <= 16 * 60 & (grepl("2MN", action, ignore.case = TRUE) | grepl("Dis", action, ignore.case = TRUE)) & action_equipe == "r"),
              1, 
              0
              ),
            DM_v = if_else(
              any(Temps_Sec >= 13 * 60 & Temps_Sec <= 16 * 60 & (grepl("2MN", action, ignore.case = TRUE) | grepl("Dis", action, ignore.case = TRUE)) & action_equipe == "v"),
              1, 
              0
              )
            ) %>%
  filter(abs(score_recevant_15_min - score_visiteur_15_min) <= 3) %>% 
  pivot_longer(
    cols = c(statut_15_min_r, statut_15_min_v), 
    names_to = "equipe", 
    values_to = "statut_15_min"
  ) %>%
  mutate(
    equipe = case_when(
      equipe == "statut_15_min_r" ~ "R",
      equipe == "statut_15_min_v" ~ "V",
    ),
    statut_16_min = case_when(
      equipe == "R" ~ statut_16_min_r,
      equipe == "V" ~ statut_16_min_v,
    ),
    statut_final = case_when(
      equipe == "R" & score_final_r > score_final_v ~ 1,
      equipe == "V" & score_final_v > score_final_r ~ 1,
      score_final_v == score_final_r ~ 0,
      equipe == "R" & score_final_r < score_final_v ~ -1,
      equipe == "V" & score_final_v < score_final_r ~ -1,
    ),
    effet_positif = case_when(
      statut_15_min == -1 & (statut_16_min == 0 | statut_16_min == 1) ~ 1,
      statut_15_min == 1 & statut_16_min == 1 ~ 1,
      statut_15_min == 0 & statut_16_min == 1 ~ 1,
      TRUE ~ 0
    ),
    TM_derniere_min = case_when(
      equipe == "R" & TM_derniere_min_r == 1 ~ 1,
      equipe == "V" & TM_derniere_min_v == 1 ~ 1,
      TRUE ~ 0
    ),
    TM_derniere_min_adverse = case_when(
      equipe == "V" & TM_derniere_min_r == 1 ~ 1,
      equipe == "R" & TM_derniere_min_v == 1 ~ 1,
      TRUE ~ 0
    ),
    HF = case_when(
      grepl("D1F", fichier, ignore.case = TRUE) | grepl("D2F", fichier, ignore.case = TRUE) ~ "F",
      TRUE ~ "H"
    ),
     DM = case_when(
      equipe == "R" & DM_r == 1 ~ 1,
      equipe == "V" & DM_v == 1 ~ 1,
      TRUE ~ 0
    ),
    DM_adverse = case_when(
      equipe == "V" & DM_r == 1 ~ 1,
      equipe == "R" & DM_v == 1 ~ 1,
      TRUE ~ 0
    ),
    division = case_when(
      grepl("D1", fichier, ignore.case = TRUE) ~ "D1",
      grepl("D2", fichier, ignore.case = TRUE) ~ "D2"
    ),
    saison = case_when(
      grepl("2223", fichier, ignore.case = TRUE) ~ "2223",
      grepl("2324", fichier, ignore.case = TRUE) ~ "2324"
    )
  ) %>% 
  select(-c(TM_derniere_min_r, TM_derniere_min_v, DM_r, DM_v, temps_proche_15_min, statut_16_min_r, statut_16_min_v))

data_mod3 <- data_mod3 %>%
  filter(equipe == "R") %>% 
  filter(statut_15_min != 0 | statut_16_min != 0)

```

```{r}
data_mod3$equipe <- factor(data_mod3$equipe)
data_mod3$statut_15_min <- factor(data_mod3$statut_15_min)
data_mod3$statut_16_min <- factor(data_mod3$statut_16_min)
data_mod3$statut_final <- factor(data_mod3$statut_final)
data_mod3$effet_positif <- factor(data_mod3$effet_positif)
data_mod3$TM_derniere_min <- factor(data_mod3$TM_derniere_min)
data_mod3$TM_derniere_min_adverse <- factor(data_mod3$TM_derniere_min_adverse)
data_mod3$HF <- factor(data_mod3$HF)
data_mod3$DM <- factor(data_mod3$DM)
data_mod3$DM_adverse <- factor(data_mod3$DM_adverse)
```


```{r}
# Graphique pour effet_positif
ggplot(data.frame(Var = names(table(data_mod3$effet_positif)), 
                  Freq = as.numeric(table(data_mod3$effet_positif))), aes(x = Var, y = Freq, fill = Var)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = Freq), vjust = -0.5) +
  labs(title = "Distribution de effet_positif", x = "Effet positif", y = "Fréquence") +
  scale_fill_manual(values = c("red", "green3")) +
  theme_minimal() +
  theme(legend.position = "none")

# Graphique pour TM_derniere_min
ggplot(data.frame(Var = names(table(data_mod3$TM_derniere_min)), 
                  Freq = as.numeric(table(data_mod3$TM_derniere_min))), aes(x = Var, y = Freq, fill = Var)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = Freq), vjust = -0.5) +
  labs(title = "Distribution de TM_derniere_min", x = "Temps mort à la dernière minute", y = "Fréquence") +
  scale_fill_manual(values = c("skyblue", "orange")) +
  theme_minimal() +
  theme(legend.position = "none")


# Graphique pour HF
ggplot(data.frame(Var = names(table(data_mod3$HF)), 
                  Freq = as.numeric(table(data_mod3$HF))), aes(x = Var, y = Freq, fill = Var)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = Freq), vjust = -0.5) +
  labs(title = "Distribution de HF", x = "Hommes ou femmes", y = "Fréquence") +
  scale_fill_manual(values = c("skyblue", "orange")) +
  theme_minimal() +
  theme(legend.position = "none")

# Graphique pour DM_adverse
ggplot(data.frame(Var = names(table(data_mod3$DM_adverse)), 
                  Freq = as.numeric(table(data_mod3$DM_adverse))), aes(x = Var, y = Freq, fill = Var)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = Freq), vjust = -0.5) +
  labs(title = "Distribution de DM_adverse", x = "2min de l'adversaire", y = "Fréquence") +
  scale_fill_manual(values = c("skyblue", "orange")) +
  theme_minimal() +
  theme(legend.position = "none")


# Graphique pour Statut
ggplot(data.frame(Var = names(table(data_mod3$statut_15_min)), 
                  Freq = as.numeric(table(data_mod3$statut_15_min))), aes(x = Var, y = Freq, fill = Var)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = Freq), vjust = -0.5) +
  labs(title = "Distribution de Statut_15_min", x = "Statut recevant à 15min", y = "Fréquence") +
  scale_fill_manual(values = c("skyblue", "orange", "green")) +
  theme_minimal() +
  theme(legend.position = "none")
```

```{r}
mod3 <- glm(effet_positif ~ TM_derniere_min + TM_derniere_min_adverse + HF + DM_adverse + DM, data = data_mod3, family = "binomial")
summary(mod3)

stepwise(mod3, direction = "forward/backward", criterion = "AIC")
```

```{r}
data_egalite_3 <- data_mod3 %>% 
  filter(statut_15_min == "0")

mod_egalite4 <- glm(effet_positif ~ TM_derniere_min + TM_derniere_min_adverse + HF + DM_adverse + DM, data = data_egalite_3, family = "binomial")
summary(mod_egalite4)

stepwise(mod_egalite4, direction = "forward/backward", criterion = "AIC")
```

```{r}
data_perdant_3 <- data_mod3 %>% 
  filter(statut_15_min == "-1")

mod_perdant4 <- glm(effet_positif ~ TM_derniere_min + TM_derniere_min_adverse + HF + DM_adverse + DM, data = data_perdant_3, family = "binomial")
summary(mod_perdant4)

stepwise(mod_perdant41, direction = "forward/backward", criterion = "AIC")
```

```{r}
data_gagnant_3 <- data_mod3 %>% 
  filter(statut_15_min == "1")

mod_gagnant4 <- glm(effet_positif ~ TM_derniere_min + TM_derniere_min_adverse + HF + DM_adverse + DM, data = data_gagnant_3, family = "binomial")
summary(mod_gagnant4)

stepwise(mod_gagnant4, direction = "forward/backward", criterion = "AIC")
```