---
title: "Prédictions"
author: "Marine"
date: "2025-01-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#importations

```{r}
library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(RcmdrMisc)
library(GGally)
library(cvTools)
library(pROC)
library(caret)
```


#Jeu de données initial

```{r}
data <- read.csv("Data/df_pdfs.csv", header = TRUE, sep = ",")

data <- data %>%
  separate(score_final, into = c("score_final_r", "score_final_v"), sep = "-") %>%
  mutate(
    score_final_r = as.integer(score_final_r),
    score_final_v = as.integer(score_final_v)
  )

data_mod1 <- data %>%
  group_by(code_rencontre, club_recevant, coach_recevant, club_visiteur, coach_visiteur, journee, score_final_r, score_final_v, fichier) %>%
  summarise(temps_proche_59_min = max(Temps_Sec[Temps_Sec < 59 * 60], na.rm = TRUE),
            statut_59_min_r = first(statut_recevant[Temps_Sec == temps_proche_59_min]),
            statut_59_min_v = -statut_59_min_r,
            score_recevant_59_min = first(score_recevant[Temps_Sec == temps_proche_59_min]),
            score_visiteur_59_min = first(score_visiteur[Temps_Sec == temps_proche_59_min]),
            TM_derniere_min_r = if_else(
              any(Temps_Sec >= 59 * 60 & grepl("tem", action, ignore.case = TRUE) & action_equipe == "r"),
              1, 
              0
              ),
            TM_derniere_min_v = if_else(
              any(Temps_Sec >= 59 * 60 & grepl("tem", action, ignore.case = TRUE) & action_equipe == "v"),
              1, 
              0
              ),
            DM_r = if_else(
              any(Temps_Sec >= 57 * 60 & (grepl("2MN", action, ignore.case = TRUE) | grepl("Dis", action, ignore.case = TRUE)) & action_equipe == "r"),
              1, 
              0
              ),
            DM_v = if_else(
              any(Temps_Sec >= 57 * 60 & (grepl("2MN", action, ignore.case = TRUE) | grepl("Dis", action, ignore.case = TRUE)) & action_equipe == "v"),
              1, 
              0
              ),
            .groups = "drop"
            ) %>%
  filter(abs(score_recevant_59_min - score_visiteur_59_min) <= 3) %>% 
  pivot_longer(
    cols = c(statut_59_min_r, statut_59_min_v), 
    names_to = "equipe", 
    values_to = "statut_59_min"
  ) %>%
  mutate(
    equipe = case_when(
      equipe == "statut_59_min_r" ~ "R",
      equipe == "statut_59_min_v" ~ "V"
    ),
    statut_final = case_when(
      equipe == "R" & score_final_r > score_final_v ~ 1,
      equipe == "V" & score_final_v > score_final_r ~ 1,
      score_final_v == score_final_r ~ 0,
      equipe == "R" & score_final_r < score_final_v ~ -1,
      equipe == "V" & score_final_v < score_final_r ~ -1,
    ),
    effet_positif = case_when(
      statut_59_min == -1 & (statut_final == 0 | statut_final == 1) ~ 1,
      statut_59_min == 1 & statut_final == 1 ~ 1,
      statut_59_min == 0 & statut_final == 1 ~ 1,
      TRUE ~ 0
    ),
    TM_derniere_min = case_when(
      equipe == "R" & TM_derniere_min_r == 1 ~ 1,
      equipe == "V" & TM_derniere_min_v == 1 ~ 1,
      TRUE ~ 0
    ),
    TM_derniere_min_adverse = case_when(
      equipe == "V" & TM_derniere_min_r == 1 ~ 1,
      equipe == "R" & TM_derniere_min_v == 1 ~ 1,
      TRUE ~ 0
    ),
    HF = case_when(
      grepl("D1F", fichier, ignore.case = TRUE) | grepl("D2F", fichier, ignore.case = TRUE) ~ "F",
      TRUE ~ "H"
    ),
     DM = case_when(
      equipe == "R" & DM_r == 1 ~ 1,
      equipe == "V" & DM_v == 1 ~ 1,
      TRUE ~ 0
    ),
    DM_adverse = case_when(
      equipe == "V" & DM_r == 1 ~ 1,
      equipe == "R" & DM_v == 1 ~ 1,
      TRUE ~ 0
    ),
    division = case_when(
      grepl("D1", fichier, ignore.case = TRUE) ~ "D1",
      grepl("D2", fichier, ignore.case = TRUE) ~ "D2"
    ),
    saison = case_when(
      grepl("2021", fichier, ignore.case = TRUE) ~ "2021",
      grepl("2122", fichier, ignore.case = TRUE) ~ "2122",
      grepl("2223", fichier, ignore.case = TRUE) ~ "2223",
      grepl("2324", fichier, ignore.case = TRUE) ~ "2324"
    )
  ) %>% 
  select(-c(TM_derniere_min_r, TM_derniere_min_v, DM_r, DM_v, temps_proche_59_min)) %>% 
  ungroup()

# One ne garde que l'équipe recevante 
data_mod1 <- data_mod1 %>%
  filter(equipe == "R") %>% 
  filter(statut_59_min != 0 | statut_final != 0)

```


# Mise en facteur

```{r}
data_mod1$statut_59_min <- factor(data_mod1$statut_59_min)
data_mod1$statut_final <- factor(data_mod1$statut_final)
data_mod1$effet_positif <- factor(data_mod1$effet_positif)
data_mod1$TM_derniere_min <- factor(data_mod1$TM_derniere_min)
data_mod1$TM_derniere_min_adverse <- factor(data_mod1$TM_derniere_min_adverse)
data_mod1$HF <- factor(data_mod1$HF)
data_mod1$DM <- factor(data_mod1$DM)
data_mod1$DM_adverse <- factor(data_mod1$DM_adverse)
data_mod1$club_recevant <- factor(data_mod1$club_recevant)
data_mod1$saison <- factor(data_mod1$saison)
data_mod1$division <- factor(data_mod1$division)
```

# Mise à jour nom 

```{r}
 data_mod1 <- data_mod1 %>% 
    mutate(club_recevant = case_when(
      club_recevant == "PARIS 92" ~ "PARIS",
      club_recevant == "HANDBALL CLERMONT AUVERGNE METROPOLE 63" ~ "HANDBALL CLERMONT AUVERGNE METROPOLE",
      club_recevant == "BOUILLARGUES HANDBALL NIMES MEDITERRANEE" ~ "BOUILLARGUES HANDBALL NIMES METROPOLE",
      club_recevant == "LE POUZIN HB 07" ~ "LE POUZIN HB",
      club_recevant == "C'CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
      club_recevant == "LIMOGES HAND 87" ~ "LIMOGES HAND",
      club_recevant == "NANCY METROPOLE HB" ~ "NANCY METROPOLE",
      club_recevant == "NANCY HANDBALL" ~ "NANCY METROPOLE",
      club_recevant == "PAYS AIX UNIVERSITE CLUB HANDBALL" ~ "PROVENCE AIX UNIVERSITE CLUB HANDBALL",
      club_recevant == "VILLEURBANNE HANDBALL ASSOCIATION" ~ "VILLEURBANNE HANDBALL",
      club_recevant == "TREMBLAY EN FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
      club_recevant == "TREMBLAY-EN-FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
      club_recevant == "TOULON METROPOLE VAR HB" ~ "TOULON METROPOLE VAR HANDBALL",
      club_recevant == "BILLERE HANDBALL" ~ "BILLERE HANDBALL PAU PYRENEES",
      club_recevant == "CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
      club_recevant == "CAVIGAL NICE SPORTS HANDBALL" ~ "CAVIGAL NICE HANDBALL",
      club_recevant == "FRONTIGNAN HANDBALL" ~ "FRONTIGNAN THAU HANDBALL",
      club_recevant == "HBC NANTAIS" ~ "HBC NANTES",
      club_recevant == "MASSY ESSONNE HB" ~ "MASSY ESSONNE HANDBALL",
      club_recevant == "NOISY-LE-GRAND HANDBALL" ~ "NOISY LE GRAND HANDBALL",
      TRUE ~ club_recevant
    ))

data_mod1 <- data_mod1 %>% 
    mutate(club_visiteur = case_when(
      club_visiteur == "PARIS 92" ~ "PARIS",
      club_visiteur == "HANDBALL CLERMONT AUVERGNE METROPOLE 63" ~ "HANDBALL CLERMONT AUVERGNE METROPOLE",
      club_visiteur == "BOUILLARGUES HANDBALL NIMES MEDITERRANEE" ~ "BOUILLARGUES HANDBALL NIMES METROPOLE",
      club_visiteur == "LE POUZIN HB 07" ~ "LE POUZIN HB",
      club_visiteur == "C'CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
      club_visiteur == "LIMOGES HAND 87" ~ "LIMOGES HAND",
      club_visiteur == "NANCY METROPOLE HB" ~ "NANCY METROPOLE",
      club_visiteur == "NANCY HANDBALL" ~ "NANCY METROPOLE",
      club_visiteur == "PAYS AIX UNIVERSITE CLUB HANDBALL" ~ "PROVENCE AIX UNIVERSITE CLUB HANDBALL",
      club_visiteur == "VILLEURBANNE HANDBALL ASSOCIATION" ~ "VILLEURBANNE HANDBALL",
      club_visiteur == "TREMBLAY EN FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
      club_visiteur == "TREMBLAY-EN-FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
      club_visiteur == "TOULON METROPOLE VAR HB" ~ "TOULON METROPOLE VAR HANDBALL",
      club_visiteur == "BILLERE HANDBALL" ~ "BILLERE HANDBALL PAU PYRENEES",
      club_visiteur == "CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
      club_visiteur == "CAVIGAL NICE SPORTS HANDBALL" ~ "CAVIGAL NICE HANDBALL",
      club_visiteur == "FRONTIGNAN HANDBALL" ~ "FRONTIGNAN THAU HANDBALL",
      club_visiteur == "HBC NANTAIS" ~ "HBC NANTES",
      club_visiteur == "MASSY ESSONNE HB" ~ "MASSY ESSONNE HANDBALL",
      club_visiteur == "NOISY-LE-GRAND HANDBALL" ~ "NOISY LE GRAND HANDBALL",
      TRUE ~ club_visiteur
    ))
```


# Ajout de la variable différence de point

```{r}
set.seed(123)
diff_norme <- read.csv("Data/data_diff_point_norme.csv", row.names = 1)
diff_norme$saison <- factor(diff_norme$saison)

data_mod1 <- data_mod1 %>% 
  left_join(diff_norme, by = join_by(code_rencontre, journee, HF, division, saison)) %>% 
  drop_na()

clustering <- kmeans(data_mod1$diff_point_norm, centers = 3)
data_mod1$group_diff_point <- factor(clustering$cluster)

table(data_mod1$group_diff_point)


ggplot(data_mod1, aes(x = group_diff_point, y = diff_point_norm, fill = group_diff_point)) +
  geom_boxplot() +
  labs(title = "Répartition des groupes créés", x = "Groupes", y = "Valeurs de A") +
  theme_minimal()

data_mod1 <- data_mod1 %>% 
  mutate(ecart_classement = case_when(
    group_diff_point == 1 ~ "moins fort",
    group_diff_point == 2 ~ "meme niveau",
    group_diff_point == 3 ~ "plus fort"
  ))

data_mod1$ecart_classement <- factor(data_mod1$ecart_classement, levels = c("moins fort","meme niveau","plus fort"))

data_mod1 %>% 
  mutate(journee_num = as.numeric(str_extract(journee, "[0-9].*")) )%>% 
  ggplot(aes(x = journee_num, y = diff_point_norm, color = ecart_classement)) +
  geom_point(size = 2, alpha = 0.7) +  # Points bien alignés
  labs(title = "Nuage de points des différences de points par journée",
       x = "Journée",
       y = "Différence de points normée") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
data_mod1 <- data_mod1[,-26]
data_mod1$ecart_classement <- as.factor(data_mod1$group_diff_point)
```


# Sous-jeux de données 

```{r}
set.seed(123)  

indices <- sample(1:nrow(data_mod1), size = nrow(data_mod1), replace = FALSE)

train_size <- floor(0.8 * length(indices))  # 80% des données pour l'entraînement
test_size <- floor(0.2 * length(indices))  # 20% des données pour le test

train_indices <- indices[1:train_size]
test_indices <- indices[(train_size + 1):(train_size + test_size)]

train_data <- data_mod1[train_indices, ]
test_data <- data_mod1[test_indices, ]
```

#validation croisée à la main

```{r}

k <- 10
segments <- cvFolds(n = nrow(train_data), K = k, type = "random")
resultats <- data.frame(Segment = integer(), Accuracy = numeric(), AUC = numeric())
cvpred <- rep(0,times=nrow(train_data))

for (k in 1:10) {
  test_indices <- which(segments$which == k)
  train <- train_data[-test_indices, ]
  valid <- train_data[test_indices, ]
  
  modele <- glm(effet_positif ~ TM_derniere_min + TM_derniere_min_adverse + DM_adverse + DM + ecart_classement, 
            data = train, family = "binomial")
  select <- stepwise(modele, direction = "backward/forward", criterion = "BIC")
  modele <- glm(formula(select), data = train, family = "binomial")
  probabilites <- predict(modele, newdata = valid, type = "response")
  predictions <- ifelse(probabilites > 0.5, 1, 0)
  cvpred[test_indices] <- predictions
  print(k)
}
```

# avec caret 


```{r}

train_control <- trainControl(
  method = "cv",  
  number = 10 
)

set.seed(123)  
model <- train(
  effet_positif ~ TM_derniere_min + TM_derniere_min_adverse + DM_adverse + DM + ecart_classement,
  data = train_data,   
  method = "glm", 
  family = "binomial",
  trControl = train_control,
  metric = "accuracy"  
)

print(model)

pred_prob <- predict(model, newdata = test_data, type = "prob")
pred_class <- ifelse(pred_prob[, "1"] > 0.5, 1, 0)

mean(test_data$effet_positif == pred_class)
```



#Evaluation du modèle 

```{r}
# Entraînement final sur toutes les données d'entraînement (train_data)
final_model <- glm(effet_positif ~ TM_derniere_min + TM_derniere_min_adverse + DM_adverse + DM + ecart_classement, 
                   data = train_data, family = "binomial")

# Prédictions sur le jeu de test
test_probabilities <- predict(final_model, newdata = test_data, type = "response")
test_predictions <- ifelse(test_probabilities > 0.5, 1, 0)

# Calcul de la table de confusion
confusion_matrix <- table(test_data$effet_positif, test_predictions)

# Calcul de la précision (Accuracy)
accuracy_test <- mean(test_predictions == test_data$effet_positif)

# Calcul de l'AUC pour test_data
test_auc <- auc(test_data$effet_positif, test_probabilities)

# Affichage des résultats
print("Table de confusion:")
print(confusion_matrix)
print(paste("Accuracy sur test_data:", accuracy_test))
print(paste("AUC sur test_data:", test_auc))
```



