---
title: "Preparation data modèle"
author: "Amélie Brejot"
date: "2024-12-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Importations

```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(stringr)
library(broom)
library(RcmdrMisc)
library(pls)
```

# Preparation données

```{r}
data <- read.table("../df_pdfs.csv", header = TRUE, sep = ",")

prepa_data <- function(data, min){
data <- data %>%
  separate(score_final, into = c("score_final_r", "score_final_v"), sep = "-") %>%
  mutate(
    score_final_r = as.integer(score_final_r),
    score_final_v = as.integer(score_final_v)
  )

data_mod <- data %>%
  group_by(code_rencontre, club_recevant, coach_recevant, club_visiteur, coach_visiteur, journee, score_final_r, score_final_v, fichier) %>%
  summarise(temps_proche_min = max(Temps_Sec[Temps_Sec < min * 60], na.rm = TRUE),
            statut_min_r = first(statut_recevant[Temps_Sec == temps_proche_min]),
            statut_min_v = -statut_min_r,
            score_recevant_min = first(score_recevant[Temps_Sec == temps_proche_min]),
            score_visiteur_min = first(score_visiteur[Temps_Sec == temps_proche_min]),
            if (min != 59){
              temps_proche_min = max(Temps_Sec[Temps_Sec < min * 60], na.rm = TRUE)
              statut_ap_min_r = first(statut_recevant[Temps_Sec == temps_proche_min])
              statut_ap_min_v = -statut_min_r
              score_recevant_ap_min = first(score_recevant[Temps_Sec == temps_proche_min])
              score_visiteur_ap_min = first(score_visiteur[Temps_Sec == temps_proche_min])
            },
            TM_derniere_min_r = if_else(
              any(Temps_Sec >= min * 60 & grepl("tem", action, ignore.case = TRUE) & action_equipe == "r"),
              1, 
              0
              ),
            TM_derniere_min_v = if_else(
              any(Temps_Sec >= min * 60 & grepl("tem", action, ignore.case = TRUE) & action_equipe == "v"),
              1, 
              0
              ),
            DM_r = if_else(
              any(Temps_Sec >= (min-2) * 60 & (grepl("2MN", action, ignore.case = TRUE) | grepl("Dis", action, ignore.case = TRUE)) & action_equipe == "r"),
              1, 
              0
              ),
            DM_v = if_else(
              any(Temps_Sec >= (min-2) * 60 & (grepl("2MN", action, ignore.case = TRUE) | grepl("Dis", action, ignore.case = TRUE)) & action_equipe == "v"),
              1, 
              0
              )
            ) %>%
  filter(abs(score_recevant_min - score_visiteur_min) <= 3) %>% 
  pivot_longer(
    cols = c(statut_min_r, statut_min_v), 
    names_to = "equipe", 
    values_to = "statut_min"
  ) %>%
  mutate(
    equipe = case_when(
      equipe == "statut_min_r" ~ "R",
      equipe == "statut_min_v" ~ "V"
    ),
    statut_final = case_when(
      equipe == "R" & score_final_r > score_final_v ~ 1,
      equipe == "V" & score_final_v > score_final_r ~ 1,
      score_final_v == score_final_r ~ 0,
      equipe == "R" & score_final_r < score_final_v ~ -1,
      equipe == "V" & score_final_v < score_final_r ~ -1,
    ),
    effet_positif = case_when(
      statut_min == -1 & (statut_final == 0 | statut_final == 1) ~ 1,
      statut_min == 1 & statut_final == 1 ~ 1,
      statut_min == 0 & statut_final == 1 ~ 1,
      TRUE ~ 0
    ),
    TM_derniere_min = case_when(
      equipe == "R" & TM_derniere_min_r == 1 ~ 1,
      equipe == "V" & TM_derniere_min_v == 1 ~ 1,
      TRUE ~ 0
    ),
    TM_derniere_min_adverse = case_when(
      equipe == "V" & TM_derniere_min_r == 1 ~ 1,
      equipe == "R" & TM_derniere_min_v == 1 ~ 1,
      TRUE ~ 0
    ),
    HF = case_when(
      grepl("D1F", fichier, ignore.case = TRUE) | grepl("D2F", fichier, ignore.case = TRUE) ~ "F",
      TRUE ~ "H"
    ),
     DM = case_when(
      equipe == "R" & DM_r == 1 ~ 1,
      equipe == "V" & DM_v == 1 ~ 1,
      TRUE ~ 0
    ),
    DM_adverse = case_when(
      equipe == "V" & DM_r == 1 ~ 1,
      equipe == "R" & DM_v == 1 ~ 1,
      TRUE ~ 0
    ),
    division = case_when(
      grepl("D1", fichier, ignore.case = TRUE) ~ "D1",
      grepl("D2", fichier, ignore.case = TRUE) ~ "D2"
    ),
    saison = case_when(
      grepl("2021", fichier, ignore.case = TRUE) ~ "2021",
      grepl("2122", fichier, ignore.case = TRUE) ~ "2122",
      grepl("2223", fichier, ignore.case = TRUE) ~ "2223",
      grepl("2324", fichier, ignore.case = TRUE) ~ "2324"
    )
  ) %>% 
  select(-c(TM_derniere_min_r, TM_derniere_min_v, DM_r, DM_v, temps_proche_min))
  
  data_mod <- data_mod %>% 
    mutate(club_recevant = case_when(
      club_recevant == "PARIS 92" ~ "PARIS",
      club_recevant == "HANDBALL CLERMONT AUVERGNE METROPOLE 63" ~ "HANDBALL CLERMONT AUVERGNE METROPOLE",
      club_recevant == "BOUILLARGUES HANDBALL NIMES MEDITERRANEE" ~ "BOUILLARGUES HANDBALL NIMES METROPOLE",
      club_recevant == "LE POUZIN HB 07" ~ "LE POUZIN HB",
      club_recevant == "C'CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
      club_recevant == "LIMOGES HAND 87" ~ "LIMOGES HAND",
      club_recevant == "NANCY METROPOLE HB" ~ "NANCY METROPOLE",
      club_recevant == "NANCY HANDBALL" ~ "NANCY METROPOLE",
      club_recevant == "PAYS AIX UNIVERSITE CLUB HANDBALL" ~ "PROVENCE AIX UNIVERSITE CLUB HANDBALL",
      club_recevant == "VILLEURBANNE HANDBALL ASSOCIATION" ~ "VILLEURBANNE HANDBALL",
      club_recevant == "TREMBLAY EN FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
      club_recevant == "TREMBLAY-EN-FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
      club_recevant == "TOULON METROPOLE VAR HB" ~ "TOULON METROPOLE VAR HANDBALL",
      club_recevant == "BILLERE HANDBALL" ~ "BILLERE HANDBALL PAU PYRENEES",
      club_recevant == "CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
      club_recevant == "CAVIGAL NICE SPORTS HANDBALL" ~ "CAVIGAL NICE HANDBALL",
      club_recevant == "FRONTIGNAN HANDBALL" ~ "FRONTIGNAN THAU HANDBALL",
      club_recevant == "HBC NANTAIS" ~ "HBC NANTES",
      club_recevant == "MASSY ESSONNE HB" ~ "MASSY ESSONNE HANDBALL",
      club_recevant == "NOISY-LE-GRAND HANDBALL" ~ "NOISY LE GRAND HANDBALL",
      TRUE ~ club_recevant
    ))
  
  data_mod <- data_mod %>% 
    mutate(club_visiteur = case_when(
      club_visiteur == "PARIS 92" ~ "PARIS",
      club_visiteur == "HANDBALL CLERMONT AUVERGNE METROPOLE 63" ~ "HANDBALL CLERMONT AUVERGNE METROPOLE",
      club_visiteur == "BOUILLARGUES HANDBALL NIMES MEDITERRANEE" ~ "BOUILLARGUES HANDBALL NIMES METROPOLE",
      club_visiteur == "LE POUZIN HB 07" ~ "LE POUZIN HB",
      club_visiteur == "C'CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
      club_visiteur == "LIMOGES HAND 87" ~ "LIMOGES HAND",
      club_visiteur == "NANCY METROPOLE HB" ~ "NANCY METROPOLE",
      club_visiteur == "NANCY HANDBALL" ~ "NANCY METROPOLE",
      club_visiteur == "PAYS AIX UNIVERSITE CLUB HANDBALL" ~ "PROVENCE AIX UNIVERSITE CLUB HANDBALL",
      club_visiteur == "VILLEURBANNE HANDBALL ASSOCIATION" ~ "VILLEURBANNE HANDBALL",
      club_visiteur == "TREMBLAY EN FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
      club_visiteur == "TREMBLAY-EN-FRANCE HANDBALL" ~ "TREMBLAY HANDBALL",
      club_visiteur == "TOULON METROPOLE VAR HB" ~ "TOULON METROPOLE VAR HANDBALL",
      club_visiteur == "BILLERE HANDBALL" ~ "BILLERE HANDBALL PAU PYRENEES",
      club_visiteur == "CHARTRES HANDBALL" ~ "C'CHARTRES METROPOLE HANDBALL",
      club_visiteur == "CAVIGAL NICE SPORTS HANDBALL" ~ "CAVIGAL NICE HANDBALL",
      club_visiteur == "FRONTIGNAN HANDBALL" ~ "FRONTIGNAN THAU HANDBALL",
      club_visiteur == "HBC NANTAIS" ~ "HBC NANTES",
      club_visiteur == "MASSY ESSONNE HB" ~ "MASSY ESSONNE HANDBALL",
      club_visiteur == "NOISY-LE-GRAND HANDBALL" ~ "NOISY LE GRAND HANDBALL",
      TRUE ~ club_visiteur
    ))
  
}

data_mod1 <- prepa_data(data, 29)

# On ne garde que l'équipe recevante 
data_mod1 <- data_mod1 %>%
  filter(equipe == "R") %>% 
  filter(statut_min != 0 | statut_final != 0)
```

# Mise en facteur

```{r}
facteur <- function(data){
  data$equipe <- factor(data$equipe)
  data$statut_min <- factor(data$statut_min)
  data$statut_final <- factor(data$statut_final)
  data$effet_positif <- factor(data$effet_positif)
  data$TM_derniere_min <- factor(data$TM_derniere_min)
  data$TM_derniere_min_adverse <- factor(data$TM_derniere_min_adverse)
  data$HF <- factor(data$HF)
  data$DM <- factor(data$DM)
  data$DM_adverse <- factor(data$DM_adverse)
  data$saison <- factor(data$saison)
  return (data)
}

data_mod1 <- facteur(data_mod1)
```

# Point par jour

```{r}
point_jour_F <- read.csv("../point_jour_F.csv", row.names = 1)
point_jour_F$HF <- 'F'
point_jour_F$J0 <- 0
point_jour_F <- point_jour_F %>% relocate('J0', .after = 'total_point')
point_jour_H <- read.csv("../point_jour_H.csv", row.names = 1)
point_jour_H$J0 <- 0
point_jour_H <- point_jour_H %>% relocate('J0', .after = 'total_point')

for (j in 32:7){
  point_jour_F[,j] <- point_jour_F[,j-1]
}

for (j in 37:8){
  point_jour_H[,j] <- point_jour_H[,j-1]
}

point_jour_F <- point_jour_F %>%
  select(-J0) %>% 
  pivot_longer(cols = starts_with("J"), names_to = "journee", values_to = "points") %>%
  mutate(journee = toupper(journee))

point_jour_H <- point_jour_H %>%
  select(-J0) %>% 
  pivot_longer(cols = starts_with("J"), names_to = "journee", values_to = "points") %>%
  mutate(journee = toupper(journee))

point_jour_final <- bind_rows(point_jour_F, point_jour_H)
point_jour_final$saison <- factor(point_jour_final$saison)

data_mod1 <- data_mod1 %>% 
  left_join(point_jour_final, by = c("HF","division","saison", "journee","club_recevant"="club")) %>% 
  mutate(points_recevant = points) %>% 
  select(-c(match_joue, total_point, points))

data_mod1 <- data_mod1 %>% 
  left_join(point_jour_final, by = c("HF","division","saison", "journee","club_visiteur"="club")) %>% 
  mutate(points_visiteur = points) %>% 
  select(-c(match_joue, total_point, points))

data_mod1 <- data_mod1 %>% 
  mutate (diff_point = points_recevant - points_visiteur)

# NA dus à l'absence de certaines fdm en D1H_2021 et D2H_2021
```

# Différence de point normée

```{r}
diff_norme <- read.csv("../data_diff_point_norme.csv", row.names = 1)
diff_norme$saison <- factor(diff_norme$saison)

data_mod1 <- data_mod1 %>% 
  left_join(diff_norme, by = join_by(code_rencontre, journee, HF, division, saison))
```

# Telecharger les data 29min et 59min

```{r}
# write_csv(data_mod1, "data_mod_59min.csv")
# write_csv(data_mod1, "data_mod_29min.csv")
```
